package lua_engine

import (
	"os"
)

type DocumentationGenerator struct {
	registry *MethodRegistry
}

func NewDocumentationGenerator() *DocumentationGenerator {
	return &DocumentationGenerator{
		registry: GetRegistry(),
	}
}

func (dg *DocumentationGenerator) GenerateLuaDocumentation() string {
	return dg.registry.GenerateLuaDocumentation()
}

func (dg *DocumentationGenerator) GenerateMarkdownDocumentation() string {
	doc := "# AutoGo Lua API 文档\n\n"
	doc += "本文档描述了 AutoGo Lua 引擎中可用的所有 API。\n\n"
	doc += "## 目录\n\n"
	doc += "- [应用管理 (app)](#应用管理-app)\n"
	doc += "- [设备管理 (device)](#设备管理-device)\n"
	doc += "- [触摸操作 (touch)](#触摸操作-touch)\n"
	doc += "- [文件操作 (files)](#文件操作-files)\n"
	doc += "- [图像处理 (images)](#图像处理-images)\n"
	doc += "- [存储管理 (storages)](#存储管理-storages)\n"
	doc += "- [系统管理 (system)](#系统管理-system)\n"
	doc += "- [网络请求 (http)](#网络请求-http)\n"
	doc += "- [媒体管理 (media)](#媒体管理-media)\n"
	doc += "- [图像识别 (opencv)](#图像识别-opencv)\n"
	doc += "- [文字识别 (ppocr)](#文字识别-ppocr)\n"
	doc += "- [协程管理 (coroutine)](#协程管理-coroutine)\n"
	doc += "- [方法管理 (method)](#方法管理-method)\n\n"

	doc += "---\n\n"
	doc += "## 应用管理 (app)\n\n"
	doc += "### `app_currentPackage()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取当前页面应用包名。\n\n"
	doc += "### `app_currentActivity()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取当前页面应用类名。\n\n"
	doc += "### `app_launch(packageName: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "通过应用包名启动应用。如果该包名对应的应用不存在，则返回 `false`；否则返回 `true`。\n\n"
	doc += "### `app_openAppSetting(packageName: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "打开应用的详情页(设置页)。如果找不到该应用，返回 `false`；否则返回 `true`。\n\n"
	doc += "### `app_viewFile(path: string)`\n\n"
	doc += "用其他应用查看文件。文件不存在的情况由查看文件的应用处理。\n\n"
	doc += "### `app_editFile(path: string)`\n\n"
	doc += "用其他应用编辑文件。文件不存在的情况由编辑文件的应用处理。\n\n"
	doc += "### `app_uninstall(packageName: string)`\n\n"
	doc += "卸载应用。\n\n"
	doc += "### `app_install(path: string)`\n\n"
	doc += "安装应用。\n\n"
	doc += "### `app_isInstalled(packageName: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "判断是否已经安装某个应用。\n\n"
	doc += "### `app_clear(packageName: string)`\n\n"
	doc += "清除应用数据。\n\n"
	doc += "### `app_forceStop(packageName: string)`\n\n"
	doc += "强制停止应用。\n\n"
	doc += "### `app_disable(packageName: string)`\n\n"
	doc += "禁用应用。\n\n"
	doc += "### `app_ignoreBattOpt(packageName: string)`\n\n"
	doc += "忽略电池优化。\n\n"
	doc += "### `app_enable(packageName: string)`\n\n"
	doc += "启用应用。\n\n"
	doc += "### `app_getBrowserPackage()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取系统默认浏览器包名。\n\n"
	doc += "### `app_openUrl(url: string)`\n\n"
	doc += "用浏览器打开网站 url。\n\n"

	doc += "---\n\n"
	doc += "## 设备管理 (device)\n\n"
	doc += "### `device.width(displayId: number)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "设备分辨率宽度，横屏和竖屏时的数值不同。\n\n"
	doc += "### `device.height(displayId: number)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "设备分辨率高度，横屏和竖屏时的数值不同。\n\n"
	doc += "### `device.sdkInt`\n"
	doc += "**类型**: `number` (只读)\n\n"
	doc += "安卓系统 API 版本。例如安卓 4.4 的 sdkInt 为 19。\n\n"
	doc += "### `device.cpuAbi`\n"
	doc += "**类型**: `string` (只读)\n\n"
	doc += "设备的 CPU 架构，如 `\"arm64-v8a\"`, `\"x86\"`, `\"x86_64\"`。\n\n"
	doc += "### `device_getImei()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回设备的 IMEI。\n\n"
	doc += "### `device_getAndroidId()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回设备的 Android ID。\n\n"
	doc += "### `device_getWifiMac()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取设备 WIFI-MAC。\n\n"
	doc += "### `device_getWlanMac()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取设备以太网 MAC。\n\n"
	doc += "### `device_getIp()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取设备局域网 IP 地址。\n\n"
	doc += "### `device_getBrightness()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回当前的(手动)亮度。范围为 0~255。\n\n"
	doc += "### `device_getBrightnessMode()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回当前亮度模式，0 为手动亮度，1 为自动亮度。\n\n"
	doc += "### `device_getMusicVolume()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回当前媒体音量。\n\n"
	doc += "### `device_getNotificationVolume()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回当前通知音量。\n\n"
	doc += "### `device_getAlarmVolume()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回当前闹钟音量。\n\n"
	doc += "### `device_getMusicMaxVolume()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回媒体音量的最大值。\n\n"
	doc += "### `device_getNotificationMaxVolume()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回通知音量的最大值。\n\n"
	doc += "### `device_getAlarmMaxVolume()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回闹钟音量的最大值。\n\n"
	doc += "### `device_setMusicVolume(volume: number)`\n\n"
	doc += "设置当前媒体音量。\n\n"
	doc += "### `device_setNotificationVolume(volume: number)`\n\n"
	doc += "设置当前通知音量。\n\n"
	doc += "### `device_setAlarmVolume(volume: number)`\n\n"
	doc += "设置当前闹钟音量。\n\n"
	doc += "### `device_getBattery()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回当前电量百分比。\n\n"
	doc += "### `device_getBatteryStatus()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取电池状态。1：没有充电；2：正充电；3：没插充电器；4：不充电；5：电池充满。\n\n"
	doc += "### `device_setBatteryStatus(value: number)`\n\n"
	doc += "模拟电池状态。1：没有充电；2：正充电；5：电池充满。\n\n"
	doc += "### `device_setBatteryLevel(value: number)`\n\n"
	doc += "模拟电池电量百分百 0-100。\n\n"
	doc += "### `device_getTotalMem()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回设备内存总量，单位(KB)。1MB = 1024KB。\n\n"
	doc += "### `device_getAvailMem()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "返回设备当前可用的内存，单位字节(KB)。\n\n"
	doc += "### `device_isScreenOn()`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "返回设备屏幕是否是亮着的。如果屏幕亮着，返回 `true`；否则返回 `false`。\n\n"
	doc += "### `device_isScreenUnlock()`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "返回屏幕锁是否已经解开。已经解开返回 `true`；否则返回 `false`。\n\n"
	doc += "### `device_wakeUp()`\n\n"
	doc += "唤醒设备，包括唤醒设备 CPU、屏幕等，可以用来点亮屏幕。\n\n"
	doc += "### `device_keepScreenOn()`\n\n"
	doc += "保持屏幕常亮。\n\n"
	doc += "### `device_vibrate(ms: number)`\n\n"
	doc += "使设备震动一段时间，单位毫秒，需要 root 权限。\n\n"
	doc += "### `device_cancelVibration()`\n\n"
	doc += "如果设备处于震动状态，则取消震动，需要 root 权限。\n\n"

	doc += "---\n\n"
	doc += "## 触摸操作 (touch)\n\n"
	doc += "### `touchDown(x: number, y: number, fingerID: number, displayId: number)`\n\n"
	doc += "按下屏幕。\n\n"
	doc += "### `touchMove(x: number, y: number, fingerID: number, displayId: number)`\n\n"
	doc += "移动手指。\n\n"
	doc += "### `touchUp(x: number, y: number, fingerID: number, displayId: number)`\n\n"
	doc += "抬起手指。\n\n"
	doc += "### `click(x: number, y: number, fingerID: number, displayId: number)`\n\n"
	doc += "点击。\n\n"
	doc += "### `longClick(x: number, y: number, duration: number, fingerID: number, displayId: number)`\n\n"
	doc += "长按。\n\n"
	doc += "### `swipe(x1: number, y1: number, x2: number, y2: number, duration: number, fingerID: number, displayId: number)`\n\n"
	doc += "滑动。\n\n"
	doc += "### `swipe2(x1: number, y1: number, x2: number, y2: number, duration: number, fingerID: number, displayId: number)`\n\n"
	doc += "滑动(两点)。\n\n"
	doc += "### `home(displayId: number)`\n\n"
	doc += "按下 Home 键。\n\n"
	doc += "### `back(displayId: number)`\n\n"
	doc += "按下返回键。\n\n"
	doc += "### `recents(displayId: number)`\n\n"
	doc += "按下最近任务键。\n\n"
	doc += "### `powerDialog()`\n\n"
	doc += "长按电源键。\n\n"
	doc += "### `notifications()`\n\n"
	doc += "下拉通知栏。\n\n"
	doc += "### `quickSettings()`\n\n"
	doc += "下拉快捷设置。\n\n"
	doc += "### `volumeUp(displayId: number)`\n\n"
	doc += "按下音量加键。\n\n"
	doc += "### `volumeDown(displayId: number)`\n\n"
	doc += "按下音量减键。\n\n"
	doc += "### `camera()`\n\n"
	doc += "按下相机键。\n\n"
	doc += "### `keyAction(code: number, displayId: number)`\n\n"
	doc += "按键动作。\n\n"

	doc += "---\n\n"
	doc += "## 文件操作 (files)\n\n"
	doc += "### `files_isDir(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "返回路径 path 是否是文件夹。\n\n"
	doc += "### `files_isFile(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "返回路径 path 是否是文件。\n\n"
	doc += "### `files_isEmptyDir(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "返回文件夹 path 是否为空文件夹。如果该路径并非文件夹，则直接返回 `false`。\n\n"
	doc += "### `files_create(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "创建一个文件或文件夹并返回是否创建成功。如果文件已经存在，则直接返回 `false`。\n\n"
	doc += "### `files_exists(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "返回在路径 path 处的文件是否存在。\n\n"
	doc += "### `files_ensureDir(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "确保路径 path 所在的文件夹存在。如果该路径所在文件夹不存在，则创建该文件夹。\n\n"
	doc += "### `files_read(path: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "读取文本文件 path 的所有内容并返回。\n\n"
	doc += "### `files_readBytes(path: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "读取文件 path 的所有内容并返回。\n\n"
	doc += "### `files_write(path: string, text: string)`\n\n"
	doc += "把 text 写入到文件 path 中。如果文件存在则覆盖，不存在则创建。\n\n"
	doc += "### `files_writeBytes(path: string, bytes: string)`\n\n"
	doc += "把 bytes 写入到文件 path 中。如果文件存在则覆盖，不存在则创建。\n\n"
	doc += "### `files_append(path: string, text: string)`\n\n"
	doc += "把 text 追加到文件 path 的末尾。如果文件不存在则创建。\n\n"
	doc += "### `files_appendBytes(path: string, bytes: string)`\n\n"
	doc += "把 bytes 追加到文件 path 的末尾。如果文件不存在则创建。\n\n"
	doc += "### `files_copy(fromPath: string, toPath: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "复制文件，返回是否复制成功。\n\n"
	doc += "### `files_move(fromPath: string, toPath: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "移动文件，返回是否移动成功。\n\n"
	doc += "### `files_rename(path: string, newName: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "重命名文件，并返回是否重命名成功。\n\n"
	doc += "### `files_remove(path: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "删除文件或文件夹，如果是文件夹会删除整个文件夹包含里面的所有文件，返回是否删除成功。\n\n"
	doc += "### `files_getName(path: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回文件的文件名。例如 `files.getName(\"/sdcard/1.txt\")` 返回 `\"1.txt\"`。\n\n"
	doc += "### `files_getNameWithoutExtension(path: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回不含拓展名的文件的文件名。例如 `files.getName(\"/sdcard/1.txt\")` 返回 `\"1\"`。\n\n"
	doc += "### `files_getExtension(path: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回文件的拓展名。例如 `files.getExtension(\"/sdcard/1.txt\")` 返回 `\"txt\"`。\n\n"
	doc += "### `files_path(relativePath: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "返回相对路径对应的绝对路径。例如 `files.path(\"./1.png\")`，如果运行这个语句的脚本位于文件夹 `\"/sdcard/脚本/\"` 中，则返回 `\"/sdcard/脚本/1.png\"`。\n\n"
	doc += "### `files_listDir(path: string)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "列出文件夹 path 下的所有文件和文件夹。\n\n"

	doc += "---\n\n"
	doc += "## 图像处理 (images)\n\n"
	doc += "### `images_pixel(x: number, y: number, displayId: number)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取指定坐标的像素颜色。\n\n"
	doc += "### `images_captureScreen(x1: number, y1: number, x2: number, y2: number, displayId: number)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "截取屏幕。\n\n"
	doc += "### `images_cmpColor(x: number, y: number, colorStr: string, sim: number, displayId: number)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "比较颜色。\n\n"
	doc += "### `images_findColor(x1: number, y1: number, x2: number, y2: number, colorStr: string, sim: number, dir: number, displayId: number)`\n"
	doc += "**返回值**: `number`, `number`\n\n"
	doc += "查找颜色。\n\n"
	doc += "### `images_getColorCountInRegion(x1: number, y1: number, x2: number, y2: number, colorStr: string, sim: number, displayId: number)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取区域内指定颜色的数量。\n\n"
	doc += "### `images_detectsMultiColors(colors: string, sim: number, displayId: number)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "检测多点颜色。\n\n"
	doc += "### `images_findMultiColors(x1: number, y1: number, x2: number, y2: number, colors: string, sim: number, dir: number, displayId: number)`\n"
	doc += "**返回值**: `number`, `number`\n\n"
	doc += "查找多点颜色。\n\n"
	doc += "### `images_readFromPath(path: string)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "从路径读取图片。\n\n"
	doc += "### `images_readFromUrl(url: string)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "从 URL 读取图片。\n\n"
	doc += "### `images_readFromBase64(base64Str: string)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "从 Base64 读取图片。\n\n"
	doc += "### `images_readFromBytes(bytes: string)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "从字节数组读取图片。\n\n"
	doc += "### `images_save(img: userdata, path: string, quality: number)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "保存图片。\n\n"
	doc += "### `images_encodeToBase64(img: userdata, format: string, quality: number)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "编码为 Base64。\n\n"
	doc += "### `images_encodeToBytes(img: userdata, format: string, quality: number)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "编码为字节数组。\n\n"
	doc += "### `images_clip(img: userdata, x1: number, y1: number, x2: number, y2: number)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "裁剪图片。\n\n"
	doc += "### `images_resize(img: userdata, width: number, height: number)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "调整图片大小。\n\n"
	doc += "### `images_rotate(img: userdata, degree: number)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "旋转图片。\n\n"
	doc += "### `images_grayscale(img: userdata)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "灰度化。\n\n"
	doc += "### `images_applyThreshold(img: userdata, threshold: number, maxVal: number, typ: string)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "应用阈值。\n\n"
	doc += "### `images_applyAdaptiveThreshold(img: userdata, maxValue: number, adaptiveMethod: string, thresholdType: string, blockSize: number, C: number)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "应用自适应阈值。\n\n"
	doc += "### `images_applyBinarization(img: userdata, threshold: number)`\n"
	doc += "**返回值**: `userdata`\n\n"
	doc += "二值化。\n\n"

	doc += "---\n\n"
	doc += "## 存储管理 (storages)\n\n"
	doc += "### `storages_get(table: string, key: string)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "从指定表中获取键值。\n\n"
	doc += "### `storages_put(table: string, key: string, value: string)`\n\n"
	doc += "写入键值对，表不存在则自动创建。\n\n"
	doc += "### `storages_remove(table: string, key: string)`\n\n"
	doc += "删除指定键。\n\n"
	doc += "### `storages_contains(table: string, key: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "判断键是否存在。\n\n"
	doc += "### `storages_getAll(table: string)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "获取所有键值对。\n\n"
	doc += "### `storages_clear(table: string)`\n\n"
	doc += "清空指定表数据。\n\n"

	doc += "---\n\n"
	doc += "## 系统管理 (system)\n\n"
	doc += "### `system_getPid(processName: string)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取进程 ID。\n\n"
	doc += "### `system_getMemoryUsage(pid: number)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取内存使用。\n\n"
	doc += "### `system_getCpuUsage(pid: number)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取 CPU 使用率。\n\n"
	doc += "### `system_restartSelf()`\n\n"
	doc += "重启自身。\n\n"
	doc += "### `system_setBootStart(enable: boolean)`\n\n"
	doc += "设置开机自启。\n\n"

	doc += "---\n\n"
	doc += "## 网络请求 (http)\n\n"
	doc += "### `http_get(url: string, timeout: number)`\n"
	doc += "**返回值**: `number`, `string`\n\n"
	doc += "发送 GET 请求。返回状态码和响应内容。\n\n"
	doc += "### `http_postMultipart(url: string, fileName: string, fileData: string)`\n"
	doc += "**返回值**: `number`, `string`\n\n"
	doc += "发送 Multipart POST 请求。返回状态码和响应内容。\n\n"

	doc += "---\n\n"
	doc += "## 媒体管理 (media)\n\n"
	doc += "### `media_scanFile(path: string)`\n\n"
	doc += "扫描路径 path 的媒体文件，将它加入媒体库中。\n\n"

	doc += "---\n\n"
	doc += "## 图像识别 (opencv)\n\n"
	doc += "### `opencv_findImage(x1: number, y1: number, x2: number, y2: number, template: string, isGray: boolean, scalingFactor: number, sim: number, displayId: number)`\n"
	doc += "**返回值**: `number`, `number`\n\n"
	doc += "在指定区域内查找匹配的图片模板。\n\n"
	doc += "**参数**:\n"
	doc += "- `x1, y1`: 区域左上角的坐标\n"
	doc += "- `x2, y2`: 区域右下角的坐标。当 x2 或 y2 为 0 时，表示使用图像的最大宽度或高度\n"
	doc += "- `template`: 模板图片的字节数组指针，表示要在区域内查找的图片\n"
	doc += "- `isGray`: 布尔值，指示是否将图像转换为灰度图进行匹配，提升匹配速度和鲁棒性\n"
	doc += "- `scalingFactor`: 缩放比例，应用于模板图片和截取的待匹配区域\n"
	doc += "- `sim`: 相似度阈值，取值范围为 0.1 到 1.0，值越高表示匹配要求越精确\n\n"
	doc += "**返回值**:\n"
	doc += "- 返回找到的图片左上角坐标。如果未找到则返回 (-1, -1)\n\n"
	doc += "**透明图支持**:\n"
	doc += "- 当模板图片为透明图时，函数会自动生成遮罩来忽略透明区域\n"
	doc += "- 透明图的判定标准：图像的四个角颜色相同，且透明像素数量占总像素数的 30% 到 99%\n\n"

	doc += "---\n\n"
	doc += "## 文字识别 (ppocr)\n\n"
	doc += "### `ppocr_ocr(x1: number, y1: number, x2: number, y2: number, colorStr: string, displayId: number)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "识别屏幕文字。\n\n"
	doc += "### `ppocr_ocrFromBase64(base64Str: string, colorStr: string)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "识别 Base64 图片文字。\n\n"
	doc += "### `ppocr_ocrFromPath(path: string, colorStr: string)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "识别文件图片文字。\n\n"

	doc += "---\n\n"
	doc += "## 协程管理 (coroutine)\n\n"
	doc += "### `coroutine_launch(fn: function, name?: string, priority?: number)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "启动一个新的协程并返回协程ID。\n\n"
	doc += "**参数**:\n"
	doc += "- `fn`: 要执行的函数\n"
	doc += "- `name`: 协程名称（可选）\n"
	doc += "- `priority`: 协程优先级（可选，默认为0）\n\n"

	doc += "### `coroutine_delay(ms: number, fn: function)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "延迟指定毫秒数后执行函数，返回协程ID。\n\n"
	doc += "**参数**:\n"
	doc += "- `ms`: 延迟的毫秒数\n"
	doc += "- `fn`: 要执行的函数\n\n"

	doc += "### `coroutine_async(fn: function)`\n"
	doc += "**返回值**: `any`\n\n"
	doc += "异步执行函数并返回结果（同步等待完成）。\n\n"
	doc += "**参数**:\n"
	doc += "- `fn`: 要执行的函数\n\n"

	doc += "### `coroutine_await(value: any)`\n"
	doc += "**返回值**: `any`\n\n"
	doc += "等待并返回传入的值（简化版本，直接返回参数值）。\n\n"
	doc += "**注意**: 当前实现为简化版本，直接返回传入的值，不进行异步等待。\n\n"
	doc += "**参数**:\n"
	doc += "- `value`: 要等待的值\n\n"

	doc += "### `coroutine_sleep(ms: number)`\n\n"
	doc += "在协程中睡眠指定的毫秒数。\n\n"
	doc += "**参数**:\n"
	doc += "- `ms`: 睡眠的毫秒数\n\n"

	doc += "### `coroutine_cancel(coroutineId: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "取消指定的协程。\n\n"
	doc += "**参数**:\n"
	doc += "- `coroutineId`: 协程ID\n\n"

	doc += "### `coroutine_getActiveCoroutines()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取活跃的协程数量。\n\n"

	doc += "### `coroutine_getCoroutineList()`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "获取协程列表，每个协程包含 id、name、state、priority、duration 信息。\n\n"

	doc += "### `coroutine_getCoroutineInfo(coroutineId: string)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "获取指定协程的详细信息。\n\n"
	doc += "**参数**:\n"
	doc += "- `coroutineId`: 协程ID\n\n"
	doc += "**返回值包含**: id、name、state、priority、startedAt、completedAt、duration、error、result\n\n"

	doc += "### `coroutine_cancelAll()`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "取消所有协程，返回取消的协程数量。\n\n"

	doc += "### `coroutine_getStats()`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "获取全局统计信息。\n\n"
	doc += "**返回值包含**: totalTasks、completed、failed、cancelled、active、pools\n\n"

	doc += "### `coroutine_createPool(name: string, maxWorkers: number, maxTasks?: number)`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "创建协程池并返回池名称。\n\n"
	doc += "**参数**:\n"
	doc += "- `name`: 协程池名称\n"
	doc += "- `maxWorkers`: 最大工作协程数\n"
	doc += "- `maxTasks`: 最大任务数（可选，默认为100）\n\n"

	doc += "### `coroutine_submitToPool(poolName: string, fn: function, priority?: number)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "提交任务到协程池。\n\n"
	doc += "**参数**:\n"
	doc += "- `poolName`: 协程池名称\n"
	doc += "- `fn`: 要执行的函数\n"
	doc += "- `priority`: 任务优先级（可选，默认为0）\n\n"

	doc += "### `coroutine_getPoolStats(poolName: string)`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "获取协程池统计信息。\n\n"
	doc += "**参数**:\n"
	doc += "- `poolName`: 协程池名称\n\n"
	doc += "**返回值包含**: name、maxWorkers、maxTasks、active、queued、workers、closed\n\n"

	doc += "### `coroutine_closePool(poolName: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "关闭协程池。\n\n"
	doc += "**参数**:\n"
	doc += "- `poolName`: 协程池名称\n\n"

	doc += "### `coroutine_listPools()`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "列出所有协程池的名称。\n\n"

	doc += "### `coroutine_setScheduleStrategy(strategy: string)`\n\n"
	doc += "设置调度策略。\n\n"
	doc += "**参数**:\n"
	doc += "- `strategy`: 调度策略（fifo 或 priority）\n\n"

	doc += "### `coroutine_getScheduleStrategy()`\n"
	doc += "**返回值**: `string`\n\n"
	doc += "获取当前调度策略。\n\n"

	doc += "### `coroutine_setPriority(name: string, priority: number)`\n\n"
	doc += "设置协程优先级。\n\n"
	doc += "**参数**:\n"
	doc += "- `name`: 协程名称\n"
	doc += "- `priority`: 优先级数值\n\n"

	doc += "### `coroutine_getPriority(name: string)`\n"
	doc += "**返回值**: `number`\n\n"
	doc += "获取协程优先级。\n\n"
	doc += "**参数**:\n"
	doc += "- `name`: 协程名称\n\n"

	doc += "---\n\n"
	doc += "## 方法管理 (method)\n\n"
	doc += "### `registerMethod(name: string, description: string, overridable: boolean)`\n\n"
	doc += "注册一个新方法。\n\n"
	doc += "### `unregisterMethod(name: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "移除一个已注册的方法。\n\n"
	doc += "### `listMethods()`\n"
	doc += "**返回值**: `table`\n\n"
	doc += "列出所有已注册的方法。\n\n"
	doc += "### `overrideMethod(name: string, newFunc: function)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "重写一个已注册的方法。\n\n"
	doc += "### `restoreMethod(name: string)`\n"
	doc += "**返回值**: `boolean`\n\n"
	doc += "恢复一个被重写的方法。\n\n"

	return doc
}

func (dg *DocumentationGenerator) SaveLuaDocumentation(filename string) error {
	luaDoc := dg.GenerateLuaDocumentation()
	return os.WriteFile(filename, []byte(luaDoc), 0644)
}

func (dg *DocumentationGenerator) SaveMarkdownDocumentation(filename string) error {
	markdownDoc := dg.GenerateMarkdownDocumentation()
	return os.WriteFile(filename, []byte(markdownDoc), 0644)
}
