//go:build android && cgo

package opencv

import (
	opencv "github.com/Dasongzi1366/AutoGo/opencv"
	"github.com/ZingYao/autogo_scriptengine/lua_engine/model"
)

// OpencvModule 在 Android CGO 环境下把 Lua VM 入口桥接到真实 AutoGo/opencv。
type OpencvModule struct{}

// New 创建 opencv Lua VM 模块实例。
func New() *OpencvModule { return &OpencvModule{} }

// Name 返回模块名。
func (m *OpencvModule) Name() string { return "opencv" }

// IsAvailable 返回当前构建环境下模块是否可用。
func (m *OpencvModule) IsAvailable() bool { return true }

// Register 注册 AutoGo opencv 的真实导出方法到 Lua VM。
func (m *OpencvModule) Register(engine model.Engine) error {
	engine.RegisterMethod("opencv.newPoint2f", "OpenCV.NewPoint2f", opencv.NewPoint2f, true)
	engine.RegisterMethod("opencv.newMat", "OpenCV.NewMat", opencv.NewMat, true)
	engine.RegisterMethod("opencv.newMatFromCMat", "OpenCV.NewMatFromCMat", opencv.NewMatFromCMat, true)
	engine.RegisterMethod("opencv.newMatWithSize", "OpenCV.NewMatWithSize", opencv.NewMatWithSize, true)
	engine.RegisterMethod("opencv.newMatWithSizes", "OpenCV.NewMatWithSizes", opencv.NewMatWithSizes, true)
	engine.RegisterMethod("opencv.newMatWithSizesWithScalar", "OpenCV.NewMatWithSizesWithScalar", opencv.NewMatWithSizesWithScalar, true)
	engine.RegisterMethod("opencv.newMatWithSizesFromBytes", "OpenCV.NewMatWithSizesFromBytes", opencv.NewMatWithSizesFromBytes, true)
	engine.RegisterMethod("opencv.newMatFromScalar", "OpenCV.NewMatFromScalar", opencv.NewMatFromScalar, true)
	engine.RegisterMethod("opencv.newMatWithSizeFromScalar", "OpenCV.NewMatWithSizeFromScalar", opencv.NewMatWithSizeFromScalar, true)
	engine.RegisterMethod("opencv.newMatFromBytes", "OpenCV.NewMatFromBytes", opencv.NewMatFromBytes, true)
	engine.RegisterMethod("opencv.eye", "OpenCV.Eye", opencv.Eye, true)
	engine.RegisterMethod("opencv.zeros", "OpenCV.Zeros", opencv.Zeros, true)
	engine.RegisterMethod("opencv.ones", "OpenCV.Ones", opencv.Ones, true)
	engine.RegisterMethod("opencv.lUT", "OpenCV.LUT", opencv.LUT, true)
	engine.RegisterMethod("opencv.absDiff", "OpenCV.AbsDiff", opencv.AbsDiff, true)
	engine.RegisterMethod("opencv.add", "OpenCV.Add", opencv.Add, true)
	engine.RegisterMethod("opencv.addWeighted", "OpenCV.AddWeighted", opencv.AddWeighted, true)
	engine.RegisterMethod("opencv.bitwiseAnd", "OpenCV.BitwiseAnd", opencv.BitwiseAnd, true)
	engine.RegisterMethod("opencv.bitwiseAndWithMask", "OpenCV.BitwiseAndWithMask", opencv.BitwiseAndWithMask, true)
	engine.RegisterMethod("opencv.bitwiseNot", "OpenCV.BitwiseNot", opencv.BitwiseNot, true)
	engine.RegisterMethod("opencv.bitwiseNotWithMask", "OpenCV.BitwiseNotWithMask", opencv.BitwiseNotWithMask, true)
	engine.RegisterMethod("opencv.bitwiseOr", "OpenCV.BitwiseOr", opencv.BitwiseOr, true)
	engine.RegisterMethod("opencv.bitwiseOrWithMask", "OpenCV.BitwiseOrWithMask", opencv.BitwiseOrWithMask, true)
	engine.RegisterMethod("opencv.bitwiseXor", "OpenCV.BitwiseXor", opencv.BitwiseXor, true)
	engine.RegisterMethod("opencv.bitwiseXorWithMask", "OpenCV.BitwiseXorWithMask", opencv.BitwiseXorWithMask, true)
	engine.RegisterMethod("opencv.batchDistance", "OpenCV.BatchDistance", opencv.BatchDistance, true)
	engine.RegisterMethod("opencv.borderInterpolate", "OpenCV.BorderInterpolate", opencv.BorderInterpolate, true)
	engine.RegisterMethod("opencv.calcCovarMatrix", "OpenCV.CalcCovarMatrix", opencv.CalcCovarMatrix, true)
	engine.RegisterMethod("opencv.cartToPolar", "OpenCV.CartToPolar", opencv.CartToPolar, true)
	engine.RegisterMethod("opencv.checkRange", "OpenCV.CheckRange", opencv.CheckRange, true)
	engine.RegisterMethod("opencv.compare", "OpenCV.Compare", opencv.Compare, true)
	engine.RegisterMethod("opencv.countNonZero", "OpenCV.CountNonZero", opencv.CountNonZero, true)
	engine.RegisterMethod("opencv.completeSymm", "OpenCV.CompleteSymm", opencv.CompleteSymm, true)
	engine.RegisterMethod("opencv.convertScaleAbs", "OpenCV.ConvertScaleAbs", opencv.ConvertScaleAbs, true)
	engine.RegisterMethod("opencv.copyMakeBorder", "OpenCV.CopyMakeBorder", opencv.CopyMakeBorder, true)
	engine.RegisterMethod("opencv.dCT", "OpenCV.DCT", opencv.DCT, true)
	engine.RegisterMethod("opencv.determinant", "OpenCV.Determinant", opencv.Determinant, true)
	engine.RegisterMethod("opencv.dFT", "OpenCV.DFT", opencv.DFT, true)
	engine.RegisterMethod("opencv.divide", "OpenCV.Divide", opencv.Divide, true)
	engine.RegisterMethod("opencv.eigen", "OpenCV.Eigen", opencv.Eigen, true)
	engine.RegisterMethod("opencv.eigenNonSymmetric", "OpenCV.EigenNonSymmetric", opencv.EigenNonSymmetric, true)
	engine.RegisterMethod("opencv.pCABackProject", "OpenCV.PCABackProject", opencv.PCABackProject, true)
	engine.RegisterMethod("opencv.pCACompute", "OpenCV.PCACompute", opencv.PCACompute, true)
	engine.RegisterMethod("opencv.pCAProject", "OpenCV.PCAProject", opencv.PCAProject, true)
	engine.RegisterMethod("opencv.pSNR", "OpenCV.PSNR", opencv.PSNR, true)
	engine.RegisterMethod("opencv.sVBackSubst", "OpenCV.SVBackSubst", opencv.SVBackSubst, true)
	engine.RegisterMethod("opencv.sVDecomp", "OpenCV.SVDecomp", opencv.SVDecomp, true)
	engine.RegisterMethod("opencv.exp", "OpenCV.Exp", opencv.Exp, true)
	engine.RegisterMethod("opencv.extractChannel", "OpenCV.ExtractChannel", opencv.ExtractChannel, true)
	engine.RegisterMethod("opencv.findNonZero", "OpenCV.FindNonZero", opencv.FindNonZero, true)
	engine.RegisterMethod("opencv.flip", "OpenCV.Flip", opencv.Flip, true)
	engine.RegisterMethod("opencv.gemm", "OpenCV.Gemm", opencv.Gemm, true)
	engine.RegisterMethod("opencv.getOptimalDFTSize", "OpenCV.GetOptimalDFTSize", opencv.GetOptimalDFTSize, true)
	engine.RegisterMethod("opencv.hconcat", "OpenCV.Hconcat", opencv.Hconcat, true)
	engine.RegisterMethod("opencv.vconcat", "OpenCV.Vconcat", opencv.Vconcat, true)
	engine.RegisterMethod("opencv.rotate", "OpenCV.Rotate", opencv.Rotate, true)
	engine.RegisterMethod("opencv.iDCT", "OpenCV.IDCT", opencv.IDCT, true)
	engine.RegisterMethod("opencv.iDFT", "OpenCV.IDFT", opencv.IDFT, true)
	engine.RegisterMethod("opencv.inRange", "OpenCV.InRange", opencv.InRange, true)
	engine.RegisterMethod("opencv.inRangeWithScalar", "OpenCV.InRangeWithScalar", opencv.InRangeWithScalar, true)
	engine.RegisterMethod("opencv.insertChannel", "OpenCV.InsertChannel", opencv.InsertChannel, true)
	engine.RegisterMethod("opencv.invert", "OpenCV.Invert", opencv.Invert, true)
	engine.RegisterMethod("opencv.kMeans", "OpenCV.KMeans", opencv.KMeans, true)
	engine.RegisterMethod("opencv.kMeansPoints", "OpenCV.KMeansPoints", opencv.KMeansPoints, true)
	engine.RegisterMethod("opencv.log", "OpenCV.Log", opencv.Log, true)
	engine.RegisterMethod("opencv.magnitude", "OpenCV.Magnitude", opencv.Magnitude, true)
	engine.RegisterMethod("opencv.mahalanobis", "OpenCV.Mahalanobis", opencv.Mahalanobis, true)
	engine.RegisterMethod("opencv.mulTransposed", "OpenCV.MulTransposed", opencv.MulTransposed, true)
	engine.RegisterMethod("opencv.max", "OpenCV.Max", opencv.Max, true)
	engine.RegisterMethod("opencv.meanStdDev", "OpenCV.MeanStdDev", opencv.MeanStdDev, true)
	engine.RegisterMethod("opencv.merge", "OpenCV.Merge", opencv.Merge, true)
	engine.RegisterMethod("opencv.min", "OpenCV.Min", opencv.Min, true)
	engine.RegisterMethod("opencv.minMaxIdx", "OpenCV.MinMaxIdx", opencv.MinMaxIdx, true)
	engine.RegisterMethod("opencv.minMaxLoc", "OpenCV.MinMaxLoc", opencv.MinMaxLoc, true)
	engine.RegisterMethod("opencv.minMaxLocWithMask", "OpenCV.MinMaxLocWithMask", opencv.MinMaxLocWithMask, true)
	engine.RegisterMethod("opencv.mixChannels", "OpenCV.MixChannels", opencv.MixChannels, true)
	engine.RegisterMethod("opencv.mulSpectrums", "OpenCV.MulSpectrums", opencv.MulSpectrums, true)
	engine.RegisterMethod("opencv.multiply", "OpenCV.Multiply", opencv.Multiply, true)
	engine.RegisterMethod("opencv.multiplyWithParams", "OpenCV.MultiplyWithParams", opencv.MultiplyWithParams, true)
	engine.RegisterMethod("opencv.normalize", "OpenCV.Normalize", opencv.Normalize, true)
	engine.RegisterMethod("opencv.norm", "OpenCV.Norm", opencv.Norm, true)
	engine.RegisterMethod("opencv.normWithMats", "OpenCV.NormWithMats", opencv.NormWithMats, true)
	engine.RegisterMethod("opencv.perspectiveTransform", "OpenCV.PerspectiveTransform", opencv.PerspectiveTransform, true)
	engine.RegisterMethod("opencv.solve", "OpenCV.Solve", opencv.Solve, true)
	engine.RegisterMethod("opencv.solveCubic", "OpenCV.SolveCubic", opencv.SolveCubic, true)
	engine.RegisterMethod("opencv.solvePoly", "OpenCV.SolvePoly", opencv.SolvePoly, true)
	engine.RegisterMethod("opencv.reduce", "OpenCV.Reduce", opencv.Reduce, true)
	engine.RegisterMethod("opencv.reduceArgMax", "OpenCV.ReduceArgMax", opencv.ReduceArgMax, true)
	engine.RegisterMethod("opencv.reduceArgMin", "OpenCV.ReduceArgMin", opencv.ReduceArgMin, true)
	engine.RegisterMethod("opencv.repeat", "OpenCV.Repeat", opencv.Repeat, true)
	engine.RegisterMethod("opencv.scaleAdd", "OpenCV.ScaleAdd", opencv.ScaleAdd, true)
	engine.RegisterMethod("opencv.setIdentity", "OpenCV.SetIdentity", opencv.SetIdentity, true)
	engine.RegisterMethod("opencv.sort", "OpenCV.Sort", opencv.Sort, true)
	engine.RegisterMethod("opencv.sortIdx", "OpenCV.SortIdx", opencv.SortIdx, true)
	engine.RegisterMethod("opencv.split", "OpenCV.Split", opencv.Split, true)
	engine.RegisterMethod("opencv.subtract", "OpenCV.Subtract", opencv.Subtract, true)
	engine.RegisterMethod("opencv.trace", "OpenCV.Trace", opencv.Trace, true)
	engine.RegisterMethod("opencv.transform", "OpenCV.Transform", opencv.Transform, true)
	engine.RegisterMethod("opencv.transpose", "OpenCV.Transpose", opencv.Transpose, true)
	engine.RegisterMethod("opencv.transposeND", "OpenCV.TransposeND", opencv.TransposeND, true)
	engine.RegisterMethod("opencv.pow", "OpenCV.Pow", opencv.Pow, true)
	engine.RegisterMethod("opencv.polarToCart", "OpenCV.PolarToCart", opencv.PolarToCart, true)
	engine.RegisterMethod("opencv.phase", "OpenCV.Phase", opencv.Phase, true)
	engine.RegisterMethod("opencv.newTermCriteria", "OpenCV.NewTermCriteria", opencv.NewTermCriteria, true)
	engine.RegisterMethod("opencv.newScalar", "OpenCV.NewScalar", opencv.NewScalar, true)
	engine.RegisterMethod("opencv.newPointVector", "OpenCV.NewPointVector", opencv.NewPointVector, true)
	engine.RegisterMethod("opencv.newPointVectorFromPoints", "OpenCV.NewPointVectorFromPoints", opencv.NewPointVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPointVectorFromMat", "OpenCV.NewPointVectorFromMat", opencv.NewPointVectorFromMat, true)
	engine.RegisterMethod("opencv.newPointsVector", "OpenCV.NewPointsVector", opencv.NewPointsVector, true)
	engine.RegisterMethod("opencv.newPointsVectorFromPoints", "OpenCV.NewPointsVectorFromPoints", opencv.NewPointsVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint2fVector", "OpenCV.NewPoint2fVector", opencv.NewPoint2fVector, true)
	engine.RegisterMethod("opencv.newPoint2fVectorFromPoints", "OpenCV.NewPoint2fVectorFromPoints", opencv.NewPoint2fVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint2fVectorFromMat", "OpenCV.NewPoint2fVectorFromMat", opencv.NewPoint2fVectorFromMat, true)
	engine.RegisterMethod("opencv.getTickCount", "OpenCV.GetTickCount", opencv.GetTickCount, true)
	engine.RegisterMethod("opencv.getTickFrequency", "OpenCV.GetTickFrequency", opencv.GetTickFrequency, true)
	engine.RegisterMethod("opencv.theRNG", "OpenCV.TheRNG", opencv.TheRNG, true)
	engine.RegisterMethod("opencv.setRNGSeed", "OpenCV.SetRNGSeed", opencv.SetRNGSeed, true)
	engine.RegisterMethod("opencv.randN", "OpenCV.RandN", opencv.RandN, true)
	engine.RegisterMethod("opencv.randShuffle", "OpenCV.RandShuffle", opencv.RandShuffle, true)
	engine.RegisterMethod("opencv.randShuffleWithParams", "OpenCV.RandShuffleWithParams", opencv.RandShuffleWithParams, true)
	engine.RegisterMethod("opencv.randU", "OpenCV.RandU", opencv.RandU, true)
	engine.RegisterMethod("opencv.newPoints2fVector", "OpenCV.NewPoints2fVector", opencv.NewPoints2fVector, true)
	engine.RegisterMethod("opencv.newPoints2fVectorFromPoints", "OpenCV.NewPoints2fVectorFromPoints", opencv.NewPoints2fVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint3f", "OpenCV.NewPoint3f", opencv.NewPoint3f, true)
	engine.RegisterMethod("opencv.newPoint3fVector", "OpenCV.NewPoint3fVector", opencv.NewPoint3fVector, true)
	engine.RegisterMethod("opencv.newPoint3fVectorFromPoints", "OpenCV.NewPoint3fVectorFromPoints", opencv.NewPoint3fVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint3fVectorFromMat", "OpenCV.NewPoint3fVectorFromMat", opencv.NewPoint3fVectorFromMat, true)
	engine.RegisterMethod("opencv.newPoints3fVector", "OpenCV.NewPoints3fVector", opencv.NewPoints3fVector, true)
	engine.RegisterMethod("opencv.newPoints3fVectorFromPoints", "OpenCV.NewPoints3fVectorFromPoints", opencv.NewPoints3fVectorFromPoints, true)
	engine.RegisterMethod("opencv.setNumThreads", "OpenCV.SetNumThreads", opencv.SetNumThreads, true)
	engine.RegisterMethod("opencv.getNumThreads", "OpenCV.GetNumThreads", opencv.GetNumThreads, true)
	engine.RegisterMethod("opencv.newRotatedRect", "OpenCV.NewRotatedRect", opencv.NewRotatedRect, true)
	engine.RegisterMethod("opencv.newRotatedRect2f", "OpenCV.NewRotatedRect2f", opencv.NewRotatedRect2f, true)
	engine.RegisterMethod("opencv.lastExceptionError", "OpenCV.LastExceptionError", opencv.LastExceptionError, true)
	engine.RegisterMethod("opencv.getLastExceptionMessage", "OpenCV.GetLastExceptionMessage", opencv.GetLastExceptionMessage, true)
	engine.RegisterMethod("opencv.clearLastException", "OpenCV.ClearLastException", opencv.ClearLastException, true)
	engine.RegisterMethod("opencv.getLastException", "OpenCV.GetLastException", opencv.GetLastException, true)
	engine.RegisterMethod("opencv.openCVResult", "OpenCV.OpenCVResult", opencv.OpenCVResult, true)
	engine.RegisterMethod("opencv.iMRead", "OpenCV.IMRead", opencv.IMRead, true)
	engine.RegisterMethod("opencv.iMReadMulti", "OpenCV.IMReadMulti", opencv.IMReadMulti, true)
	engine.RegisterMethod("opencv.iMReadMulti_WithParams", "OpenCV.IMReadMulti_WithParams", opencv.IMReadMulti_WithParams, true)
	engine.RegisterMethod("opencv.iMWrite", "OpenCV.IMWrite", opencv.IMWrite, true)
	engine.RegisterMethod("opencv.iMWriteWithParams", "OpenCV.IMWriteWithParams", opencv.IMWriteWithParams, true)
	engine.RegisterMethod("opencv.iMEncode", "OpenCV.IMEncode", opencv.IMEncode, true)
	engine.RegisterMethod("opencv.iMEncodeWithParams", "OpenCV.IMEncodeWithParams", opencv.IMEncodeWithParams, true)
	engine.RegisterMethod("opencv.iMDecode", "OpenCV.IMDecode", opencv.IMDecode, true)
	engine.RegisterMethod("opencv.iMDecodeIntoMat", "OpenCV.IMDecodeIntoMat", opencv.IMDecodeIntoMat, true)
	engine.RegisterMethod("opencv.arcLength", "OpenCV.ArcLength", opencv.ArcLength, true)
	engine.RegisterMethod("opencv.approxPolyDP", "OpenCV.ApproxPolyDP", opencv.ApproxPolyDP, true)
	engine.RegisterMethod("opencv.convexHull", "OpenCV.ConvexHull", opencv.ConvexHull, true)
	engine.RegisterMethod("opencv.convexityDefects", "OpenCV.ConvexityDefects", opencv.ConvexityDefects, true)
	engine.RegisterMethod("opencv.cvtColor", "OpenCV.CvtColor", opencv.CvtColor, true)
	engine.RegisterMethod("opencv.demosaicing", "OpenCV.Demosaicing", opencv.Demosaicing, true)
	engine.RegisterMethod("opencv.equalizeHist", "OpenCV.EqualizeHist", opencv.EqualizeHist, true)
	engine.RegisterMethod("opencv.calcHist", "OpenCV.CalcHist", opencv.CalcHist, true)
	engine.RegisterMethod("opencv.calcBackProject", "OpenCV.CalcBackProject", opencv.CalcBackProject, true)
	engine.RegisterMethod("opencv.compareHist", "OpenCV.CompareHist", opencv.CompareHist, true)
	engine.RegisterMethod("opencv.eMD", "OpenCV.EMD", opencv.EMD, true)
	engine.RegisterMethod("opencv.clipLine", "OpenCV.ClipLine", opencv.ClipLine, true)
	engine.RegisterMethod("opencv.bilateralFilter", "OpenCV.BilateralFilter", opencv.BilateralFilter, true)
	engine.RegisterMethod("opencv.blur", "OpenCV.Blur", opencv.Blur, true)
	engine.RegisterMethod("opencv.boxFilter", "OpenCV.BoxFilter", opencv.BoxFilter, true)
	engine.RegisterMethod("opencv.sqBoxFilter", "OpenCV.SqBoxFilter", opencv.SqBoxFilter, true)
	engine.RegisterMethod("opencv.dilate", "OpenCV.Dilate", opencv.Dilate, true)
	engine.RegisterMethod("opencv.dilateWithParams", "OpenCV.DilateWithParams", opencv.DilateWithParams, true)
	engine.RegisterMethod("opencv.distanceTransform", "OpenCV.DistanceTransform", opencv.DistanceTransform, true)
	engine.RegisterMethod("opencv.erode", "OpenCV.Erode", opencv.Erode, true)
	engine.RegisterMethod("opencv.erodeWithParams", "OpenCV.ErodeWithParams", opencv.ErodeWithParams, true)
	engine.RegisterMethod("opencv.erodeWithParamsAndBorderValue", "OpenCV.ErodeWithParamsAndBorderValue", opencv.ErodeWithParamsAndBorderValue, true)
	engine.RegisterMethod("opencv.boundingRect", "OpenCV.BoundingRect", opencv.BoundingRect, true)
	engine.RegisterMethod("opencv.boxPoints", "OpenCV.BoxPoints", opencv.BoxPoints, true)
	engine.RegisterMethod("opencv.boxPoints2f", "OpenCV.BoxPoints2f", opencv.BoxPoints2f, true)
	engine.RegisterMethod("opencv.contourArea", "OpenCV.ContourArea", opencv.ContourArea, true)
	engine.RegisterMethod("opencv.minAreaRect", "OpenCV.MinAreaRect", opencv.MinAreaRect, true)
	engine.RegisterMethod("opencv.minAreaRect2f", "OpenCV.MinAreaRect2f", opencv.MinAreaRect2f, true)
	engine.RegisterMethod("opencv.fitEllipse", "OpenCV.FitEllipse", opencv.FitEllipse, true)
	engine.RegisterMethod("opencv.minEnclosingCircle", "OpenCV.MinEnclosingCircle", opencv.MinEnclosingCircle, true)
	engine.RegisterMethod("opencv.findContours", "OpenCV.FindContours", opencv.FindContours, true)
	engine.RegisterMethod("opencv.findContoursWithParams", "OpenCV.FindContoursWithParams", opencv.FindContoursWithParams, true)
	engine.RegisterMethod("opencv.pointPolygonTest", "OpenCV.PointPolygonTest", opencv.PointPolygonTest, true)
	engine.RegisterMethod("opencv.connectedComponents", "OpenCV.ConnectedComponents", opencv.ConnectedComponents, true)
	engine.RegisterMethod("opencv.connectedComponentsWithParams", "OpenCV.ConnectedComponentsWithParams", opencv.ConnectedComponentsWithParams, true)
	engine.RegisterMethod("opencv.connectedComponentsWithStats", "OpenCV.ConnectedComponentsWithStats", opencv.ConnectedComponentsWithStats, true)
	engine.RegisterMethod("opencv.connectedComponentsWithStatsWithParams", "OpenCV.ConnectedComponentsWithStatsWithParams", opencv.ConnectedComponentsWithStatsWithParams, true)
	engine.RegisterMethod("opencv.matchTemplate", "OpenCV.MatchTemplate", opencv.MatchTemplate, true)
	engine.RegisterMethod("opencv.moments", "OpenCV.Moments", opencv.Moments, true)
	engine.RegisterMethod("opencv.pyrDown", "OpenCV.PyrDown", opencv.PyrDown, true)
	engine.RegisterMethod("opencv.pyrUp", "OpenCV.PyrUp", opencv.PyrUp, true)
	engine.RegisterMethod("opencv.morphologyDefaultBorderValue", "OpenCV.MorphologyDefaultBorderValue", opencv.MorphologyDefaultBorderValue, true)
	engine.RegisterMethod("opencv.morphologyEx", "OpenCV.MorphologyEx", opencv.MorphologyEx, true)
	engine.RegisterMethod("opencv.morphologyExWithParams", "OpenCV.MorphologyExWithParams", opencv.MorphologyExWithParams, true)
	engine.RegisterMethod("opencv.getStructuringElement", "OpenCV.GetStructuringElement", opencv.GetStructuringElement, true)
	engine.RegisterMethod("opencv.gaussianBlur", "OpenCV.GaussianBlur", opencv.GaussianBlur, true)
	engine.RegisterMethod("opencv.getGaussianKernel", "OpenCV.GetGaussianKernel", opencv.GetGaussianKernel, true)
	engine.RegisterMethod("opencv.getGaussianKernelWithParams", "OpenCV.GetGaussianKernelWithParams", opencv.GetGaussianKernelWithParams, true)
	engine.RegisterMethod("opencv.sobel", "OpenCV.Sobel", opencv.Sobel, true)
	engine.RegisterMethod("opencv.spatialGradient", "OpenCV.SpatialGradient", opencv.SpatialGradient, true)
	engine.RegisterMethod("opencv.laplacian", "OpenCV.Laplacian", opencv.Laplacian, true)
	engine.RegisterMethod("opencv.scharr", "OpenCV.Scharr", opencv.Scharr, true)
	engine.RegisterMethod("opencv.medianBlur", "OpenCV.MedianBlur", opencv.MedianBlur, true)
	engine.RegisterMethod("opencv.canny", "OpenCV.Canny", opencv.Canny, true)
	engine.RegisterMethod("opencv.cornerSubPix", "OpenCV.CornerSubPix", opencv.CornerSubPix, true)
	engine.RegisterMethod("opencv.goodFeaturesToTrack", "OpenCV.GoodFeaturesToTrack", opencv.GoodFeaturesToTrack, true)
	engine.RegisterMethod("opencv.grabCut", "OpenCV.GrabCut", opencv.GrabCut, true)
	engine.RegisterMethod("opencv.houghCircles", "OpenCV.HoughCircles", opencv.HoughCircles, true)
	engine.RegisterMethod("opencv.houghCirclesWithParams", "OpenCV.HoughCirclesWithParams", opencv.HoughCirclesWithParams, true)
	engine.RegisterMethod("opencv.houghLines", "OpenCV.HoughLines", opencv.HoughLines, true)
	engine.RegisterMethod("opencv.houghLinesP", "OpenCV.HoughLinesP", opencv.HoughLinesP, true)
	engine.RegisterMethod("opencv.houghLinesPWithParams", "OpenCV.HoughLinesPWithParams", opencv.HoughLinesPWithParams, true)
	engine.RegisterMethod("opencv.houghLinesPointSet", "OpenCV.HoughLinesPointSet", opencv.HoughLinesPointSet, true)
	engine.RegisterMethod("opencv.integral", "OpenCV.Integral", opencv.Integral, true)
	engine.RegisterMethod("opencv.threshold", "OpenCV.Threshold", opencv.Threshold, true)
	engine.RegisterMethod("opencv.adaptiveThreshold", "OpenCV.AdaptiveThreshold", opencv.AdaptiveThreshold, true)
	engine.RegisterMethod("opencv.arrowedLine", "OpenCV.ArrowedLine", opencv.ArrowedLine, true)
	engine.RegisterMethod("opencv.circle", "OpenCV.Circle", opencv.Circle, true)
	engine.RegisterMethod("opencv.circleWithParams", "OpenCV.CircleWithParams", opencv.CircleWithParams, true)
	engine.RegisterMethod("opencv.ellipse", "OpenCV.Ellipse", opencv.Ellipse, true)
	engine.RegisterMethod("opencv.ellipseWithParams", "OpenCV.EllipseWithParams", opencv.EllipseWithParams, true)
	engine.RegisterMethod("opencv.line", "OpenCV.Line", opencv.Line, true)
	engine.RegisterMethod("opencv.rectangle", "OpenCV.Rectangle", opencv.Rectangle, true)
	engine.RegisterMethod("opencv.rectangleWithParams", "OpenCV.RectangleWithParams", opencv.RectangleWithParams, true)
	engine.RegisterMethod("opencv.fillPoly", "OpenCV.FillPoly", opencv.FillPoly, true)
	engine.RegisterMethod("opencv.fillPolyWithParams", "OpenCV.FillPolyWithParams", opencv.FillPolyWithParams, true)
	engine.RegisterMethod("opencv.polylines", "OpenCV.Polylines", opencv.Polylines, true)
	engine.RegisterMethod("opencv.getTextSize", "OpenCV.GetTextSize", opencv.GetTextSize, true)
	engine.RegisterMethod("opencv.getTextSizeWithBaseline", "OpenCV.GetTextSizeWithBaseline", opencv.GetTextSizeWithBaseline, true)
	engine.RegisterMethod("opencv.putText", "OpenCV.PutText", opencv.PutText, true)
	engine.RegisterMethod("opencv.putTextWithParams", "OpenCV.PutTextWithParams", opencv.PutTextWithParams, true)
	engine.RegisterMethod("opencv.resize", "OpenCV.Resize", opencv.Resize, true)
	engine.RegisterMethod("opencv.getRectSubPix", "OpenCV.GetRectSubPix", opencv.GetRectSubPix, true)
	engine.RegisterMethod("opencv.getRotationMatrix2D", "OpenCV.GetRotationMatrix2D", opencv.GetRotationMatrix2D, true)
	engine.RegisterMethod("opencv.warpAffine", "OpenCV.WarpAffine", opencv.WarpAffine, true)
	engine.RegisterMethod("opencv.warpAffineWithParams", "OpenCV.WarpAffineWithParams", opencv.WarpAffineWithParams, true)
	engine.RegisterMethod("opencv.warpPerspective", "OpenCV.WarpPerspective", opencv.WarpPerspective, true)
	engine.RegisterMethod("opencv.warpPerspectiveWithParams", "OpenCV.WarpPerspectiveWithParams", opencv.WarpPerspectiveWithParams, true)
	engine.RegisterMethod("opencv.watershed", "OpenCV.Watershed", opencv.Watershed, true)
	engine.RegisterMethod("opencv.applyColorMap", "OpenCV.ApplyColorMap", opencv.ApplyColorMap, true)
	engine.RegisterMethod("opencv.applyCustomColorMap", "OpenCV.ApplyCustomColorMap", opencv.ApplyCustomColorMap, true)
	engine.RegisterMethod("opencv.getPerspectiveTransform", "OpenCV.GetPerspectiveTransform", opencv.GetPerspectiveTransform, true)
	engine.RegisterMethod("opencv.getPerspectiveTransform2f", "OpenCV.GetPerspectiveTransform2f", opencv.GetPerspectiveTransform2f, true)
	engine.RegisterMethod("opencv.getAffineTransform", "OpenCV.GetAffineTransform", opencv.GetAffineTransform, true)
	engine.RegisterMethod("opencv.getAffineTransform2f", "OpenCV.GetAffineTransform2f", opencv.GetAffineTransform2f, true)
	engine.RegisterMethod("opencv.drawContours", "OpenCV.DrawContours", opencv.DrawContours, true)
	engine.RegisterMethod("opencv.drawContoursWithParams", "OpenCV.DrawContoursWithParams", opencv.DrawContoursWithParams, true)
	engine.RegisterMethod("opencv.remap", "OpenCV.Remap", opencv.Remap, true)
	engine.RegisterMethod("opencv.filter2D", "OpenCV.Filter2D", opencv.Filter2D, true)
	engine.RegisterMethod("opencv.sepFilter2D", "OpenCV.SepFilter2D", opencv.SepFilter2D, true)
	engine.RegisterMethod("opencv.logPolar", "OpenCV.LogPolar", opencv.LogPolar, true)
	engine.RegisterMethod("opencv.linearPolar", "OpenCV.LinearPolar", opencv.LinearPolar, true)
	engine.RegisterMethod("opencv.fitLine", "OpenCV.FitLine", opencv.FitLine, true)
	engine.RegisterMethod("opencv.matchShapes", "OpenCV.MatchShapes", opencv.MatchShapes, true)
	engine.RegisterMethod("opencv.newCLAHE", "OpenCV.NewCLAHE", opencv.NewCLAHE, true)
	engine.RegisterMethod("opencv.newCLAHEWithParams", "OpenCV.NewCLAHEWithParams", opencv.NewCLAHEWithParams, true)
	engine.RegisterMethod("opencv.invertAffineTransform", "OpenCV.InvertAffineTransform", opencv.InvertAffineTransform, true)
	engine.RegisterMethod("opencv.phaseCorrelate", "OpenCV.PhaseCorrelate", opencv.PhaseCorrelate, true)
	engine.RegisterMethod("opencv.createHanningWindow", "OpenCV.CreateHanningWindow", opencv.CreateHanningWindow, true)
	engine.RegisterMethod("opencv.imageToMatRGBA", "OpenCV.ImageToMatRGBA", opencv.ImageToMatRGBA, true)
	engine.RegisterMethod("opencv.imageToMatRGB", "OpenCV.ImageToMatRGB", opencv.ImageToMatRGB, true)
	engine.RegisterMethod("opencv.imageGrayToMatGray", "OpenCV.ImageGrayToMatGray", opencv.ImageGrayToMatGray, true)
	engine.RegisterMethod("opencv.accumulate", "OpenCV.Accumulate", opencv.Accumulate, true)
	engine.RegisterMethod("opencv.accumulateWithMask", "OpenCV.AccumulateWithMask", opencv.AccumulateWithMask, true)
	engine.RegisterMethod("opencv.accumulateSquare", "OpenCV.AccumulateSquare", opencv.AccumulateSquare, true)
	engine.RegisterMethod("opencv.accumulateSquareWithMask", "OpenCV.AccumulateSquareWithMask", opencv.AccumulateSquareWithMask, true)
	engine.RegisterMethod("opencv.accumulateProduct", "OpenCV.AccumulateProduct", opencv.AccumulateProduct, true)
	engine.RegisterMethod("opencv.accumulateProductWithMask", "OpenCV.AccumulateProductWithMask", opencv.AccumulateProductWithMask, true)
	engine.RegisterMethod("opencv.accumulatedWeighted", "OpenCV.AccumulatedWeighted", opencv.AccumulatedWeighted, true)
	engine.RegisterMethod("opencv.accumulatedWeightedWithMask", "OpenCV.AccumulatedWeightedWithMask", opencv.AccumulatedWeightedWithMask, true)
	engine.RegisterMethod("opencv.findImage", "OpenCV.FindImage", opencv.FindImage, true)
	engine.RegisterMethod("opencv.findImageAll", "OpenCV.FindImageAll", opencv.FindImageAll, true)
	engine.RegisterMethod("opencv.close", "OpenCV Mat.Close", (*opencv.Mat).Close, true)
	engine.RegisterMethod("opencv.fromPtr", "OpenCV Mat.FromPtr", (*opencv.Mat).FromPtr, true)
	engine.RegisterMethod("opencv.ptr", "OpenCV Mat.Ptr", (*opencv.Mat).Ptr, true)
	engine.RegisterMethod("opencv.empty", "OpenCV Mat.Empty", (*opencv.Mat).Empty, true)
	engine.RegisterMethod("opencv.closed", "OpenCV Mat.Closed", (*opencv.Mat).Closed, true)
	engine.RegisterMethod("opencv.isContinuous", "OpenCV Mat.IsContinuous", (*opencv.Mat).IsContinuous, true)
	engine.RegisterMethod("opencv.inv", "OpenCV Mat.Inv", (*opencv.Mat).Inv, true)
	engine.RegisterMethod("opencv.col", "OpenCV Mat.Col", (*opencv.Mat).Col, true)
	engine.RegisterMethod("opencv.row", "OpenCV Mat.Row", (*opencv.Mat).Row, true)
	engine.RegisterMethod("opencv.clone", "OpenCV Mat.Clone", (*opencv.Mat).Clone, true)
	engine.RegisterMethod("opencv.copyTo", "OpenCV Mat.CopyTo", (*opencv.Mat).CopyTo, true)
	engine.RegisterMethod("opencv.copyToWithMask", "OpenCV Mat.CopyToWithMask", (*opencv.Mat).CopyToWithMask, true)
	engine.RegisterMethod("opencv.convertTo", "OpenCV Mat.ConvertTo", (*opencv.Mat).ConvertTo, true)
	engine.RegisterMethod("opencv.convertToWithParams", "OpenCV Mat.ConvertToWithParams", (*opencv.Mat).ConvertToWithParams, true)
	engine.RegisterMethod("opencv.total", "OpenCV Mat.Total", (*opencv.Mat).Total, true)
	engine.RegisterMethod("opencv.size", "OpenCV Mat.Size", (*opencv.Mat).Size, true)
	engine.RegisterMethod("opencv.toBytes", "OpenCV Mat.ToBytes", (*opencv.Mat).ToBytes, true)
	engine.RegisterMethod("opencv.dataPtrUint8", "OpenCV Mat.DataPtrUint8", (*opencv.Mat).DataPtrUint8, true)
	engine.RegisterMethod("opencv.dataPtrInt8", "OpenCV Mat.DataPtrInt8", (*opencv.Mat).DataPtrInt8, true)
	engine.RegisterMethod("opencv.dataPtrUint16", "OpenCV Mat.DataPtrUint16", (*opencv.Mat).DataPtrUint16, true)
	engine.RegisterMethod("opencv.dataPtrInt16", "OpenCV Mat.DataPtrInt16", (*opencv.Mat).DataPtrInt16, true)
	engine.RegisterMethod("opencv.dataPtrFloat32", "OpenCV Mat.DataPtrFloat32", (*opencv.Mat).DataPtrFloat32, true)
	engine.RegisterMethod("opencv.dataPtrFloat64", "OpenCV Mat.DataPtrFloat64", (*opencv.Mat).DataPtrFloat64, true)
	engine.RegisterMethod("opencv.region", "OpenCV Mat.Region", (*opencv.Mat).Region, true)
	engine.RegisterMethod("opencv.reshape", "OpenCV Mat.Reshape", (*opencv.Mat).Reshape, true)
	engine.RegisterMethod("opencv.convertFp16", "OpenCV Mat.ConvertFp16", (*opencv.Mat).ConvertFp16, true)
	engine.RegisterMethod("opencv.mean", "OpenCV Mat.Mean", (*opencv.Mat).Mean, true)
	engine.RegisterMethod("opencv.meanWithMask", "OpenCV Mat.MeanWithMask", (*opencv.Mat).MeanWithMask, true)
	engine.RegisterMethod("opencv.sqrt", "OpenCV Mat.Sqrt", (*opencv.Mat).Sqrt, true)
	engine.RegisterMethod("opencv.sum", "OpenCV Mat.Sum", (*opencv.Mat).Sum, true)
	engine.RegisterMethod("opencv.patchNaNs", "OpenCV Mat.PatchNaNs", (*opencv.Mat).PatchNaNs, true)
	engine.RegisterMethod("opencv.rows", "OpenCV Mat.Rows", (*opencv.Mat).Rows, true)
	engine.RegisterMethod("opencv.cols", "OpenCV Mat.Cols", (*opencv.Mat).Cols, true)
	engine.RegisterMethod("opencv.channels", "OpenCV Mat.Channels", (*opencv.Mat).Channels, true)
	engine.RegisterMethod("opencv.type", "OpenCV Mat.Type", (*opencv.Mat).Type, true)
	engine.RegisterMethod("opencv.step", "OpenCV Mat.Step", (*opencv.Mat).Step, true)
	engine.RegisterMethod("opencv.elemSize", "OpenCV Mat.ElemSize", (*opencv.Mat).ElemSize, true)
	engine.RegisterMethod("opencv.getUCharAt", "OpenCV Mat.GetUCharAt", (*opencv.Mat).GetUCharAt, true)
	engine.RegisterMethod("opencv.getUCharAt3", "OpenCV Mat.GetUCharAt3", (*opencv.Mat).GetUCharAt3, true)
	engine.RegisterMethod("opencv.getSCharAt", "OpenCV Mat.GetSCharAt", (*opencv.Mat).GetSCharAt, true)
	engine.RegisterMethod("opencv.getSCharAt3", "OpenCV Mat.GetSCharAt3", (*opencv.Mat).GetSCharAt3, true)
	engine.RegisterMethod("opencv.getShortAt", "OpenCV Mat.GetShortAt", (*opencv.Mat).GetShortAt, true)
	engine.RegisterMethod("opencv.getShortAt3", "OpenCV Mat.GetShortAt3", (*opencv.Mat).GetShortAt3, true)
	engine.RegisterMethod("opencv.getIntAt", "OpenCV Mat.GetIntAt", (*opencv.Mat).GetIntAt, true)
	engine.RegisterMethod("opencv.getIntAt3", "OpenCV Mat.GetIntAt3", (*opencv.Mat).GetIntAt3, true)
	engine.RegisterMethod("opencv.getFloatAt", "OpenCV Mat.GetFloatAt", (*opencv.Mat).GetFloatAt, true)
	engine.RegisterMethod("opencv.getFloatAt3", "OpenCV Mat.GetFloatAt3", (*opencv.Mat).GetFloatAt3, true)
	engine.RegisterMethod("opencv.getDoubleAt", "OpenCV Mat.GetDoubleAt", (*opencv.Mat).GetDoubleAt, true)
	engine.RegisterMethod("opencv.getDoubleAt3", "OpenCV Mat.GetDoubleAt3", (*opencv.Mat).GetDoubleAt3, true)
	engine.RegisterMethod("opencv.setTo", "OpenCV Mat.SetTo", (*opencv.Mat).SetTo, true)
	engine.RegisterMethod("opencv.setUCharAt", "OpenCV Mat.SetUCharAt", (*opencv.Mat).SetUCharAt, true)
	engine.RegisterMethod("opencv.setUCharAt3", "OpenCV Mat.SetUCharAt3", (*opencv.Mat).SetUCharAt3, true)
	engine.RegisterMethod("opencv.setSCharAt", "OpenCV Mat.SetSCharAt", (*opencv.Mat).SetSCharAt, true)
	engine.RegisterMethod("opencv.setSCharAt3", "OpenCV Mat.SetSCharAt3", (*opencv.Mat).SetSCharAt3, true)
	engine.RegisterMethod("opencv.setShortAt", "OpenCV Mat.SetShortAt", (*opencv.Mat).SetShortAt, true)
	engine.RegisterMethod("opencv.setShortAt3", "OpenCV Mat.SetShortAt3", (*opencv.Mat).SetShortAt3, true)
	engine.RegisterMethod("opencv.setIntAt", "OpenCV Mat.SetIntAt", (*opencv.Mat).SetIntAt, true)
	engine.RegisterMethod("opencv.setIntAt3", "OpenCV Mat.SetIntAt3", (*opencv.Mat).SetIntAt3, true)
	engine.RegisterMethod("opencv.setFloatAt", "OpenCV Mat.SetFloatAt", (*opencv.Mat).SetFloatAt, true)
	engine.RegisterMethod("opencv.setFloatAt3", "OpenCV Mat.SetFloatAt3", (*opencv.Mat).SetFloatAt3, true)
	engine.RegisterMethod("opencv.setDoubleAt", "OpenCV Mat.SetDoubleAt", (*opencv.Mat).SetDoubleAt, true)
	engine.RegisterMethod("opencv.setDoubleAt3", "OpenCV Mat.SetDoubleAt3", (*opencv.Mat).SetDoubleAt3, true)
	engine.RegisterMethod("opencv.addUChar", "OpenCV Mat.AddUChar", (*opencv.Mat).AddUChar, true)
	engine.RegisterMethod("opencv.subtractUChar", "OpenCV Mat.SubtractUChar", (*opencv.Mat).SubtractUChar, true)
	engine.RegisterMethod("opencv.multiplyUChar", "OpenCV Mat.MultiplyUChar", (*opencv.Mat).MultiplyUChar, true)
	engine.RegisterMethod("opencv.divideUChar", "OpenCV Mat.DivideUChar", (*opencv.Mat).DivideUChar, true)
	engine.RegisterMethod("opencv.addFloat", "OpenCV Mat.AddFloat", (*opencv.Mat).AddFloat, true)
	engine.RegisterMethod("opencv.subtractFloat", "OpenCV Mat.SubtractFloat", (*opencv.Mat).SubtractFloat, true)
	engine.RegisterMethod("opencv.multiplyFloat", "OpenCV Mat.MultiplyFloat", (*opencv.Mat).MultiplyFloat, true)
	engine.RegisterMethod("opencv.divideFloat", "OpenCV Mat.DivideFloat", (*opencv.Mat).DivideFloat, true)
	engine.RegisterMethod("opencv.multiplyMatrix", "OpenCV Mat.MultiplyMatrix", (*opencv.Mat).MultiplyMatrix, true)
	engine.RegisterMethod("opencv.t", "OpenCV Mat.T", (*opencv.Mat).T, true)
	engine.RegisterMethod("opencv.getVecbAt", "OpenCV Mat.GetVecbAt", (*opencv.Mat).GetVecbAt, true)
	engine.RegisterMethod("opencv.getVecfAt", "OpenCV Mat.GetVecfAt", (*opencv.Mat).GetVecfAt, true)
	engine.RegisterMethod("opencv.getVecdAt", "OpenCV Mat.GetVecdAt", (*opencv.Mat).GetVecdAt, true)
	engine.RegisterMethod("opencv.getVeciAt", "OpenCV Mat.GetVeciAt", (*opencv.Mat).GetVeciAt, true)
	engine.RegisterMethod("opencv.rowRange", "OpenCV Mat.RowRange", (*opencv.Mat).RowRange, true)
	engine.RegisterMethod("opencv.colRange", "OpenCV Mat.ColRange", (*opencv.Mat).ColRange, true)
	engine.RegisterMethod("opencv.toImage", "OpenCV Mat.ToImage", (*opencv.Mat).ToImage, true)
	engine.RegisterMethod("opencv.toImageYUV", "OpenCV Mat.ToImageYUV", (*opencv.Mat).ToImageYUV, true)
	engine.RegisterMethod("opencv.toImageYUVWithParams", "OpenCV Mat.ToImageYUVWithParams", (*opencv.Mat).ToImageYUVWithParams, true)
	engine.RegisterMethod("opencv.isNil", "OpenCV PointVector.IsNil", opencv.PointVector.IsNil, true)
	engine.RegisterMethod("opencv.at", "OpenCV PointVector.At", opencv.PointVector.At, true)
	engine.RegisterMethod("opencv.append", "OpenCV PointVector.Append", opencv.PointVector.Append, true)
	engine.RegisterMethod("opencv.toPoints", "OpenCV PointVector.ToPoints", opencv.PointVector.ToPoints, true)
	engine.RegisterMethod("opencv.p", "OpenCV PointsVector.P", opencv.PointsVector.P, true)
	engine.RegisterMethod("opencv.fill", "OpenCV RNG.Fill", (*opencv.RNG).Fill, true)
	engine.RegisterMethod("opencv.gaussian", "OpenCV RNG.Gaussian", (*opencv.RNG).Gaussian, true)
	engine.RegisterMethod("opencv.next", "OpenCV RNG.Next", (*opencv.RNG).Next, true)
	engine.RegisterMethod("opencv.getBytes", "OpenCV NativeByteBuffer.GetBytes", (*opencv.NativeByteBuffer).GetBytes, true)
	engine.RegisterMethod("opencv.len", "OpenCV NativeByteBuffer.Len", (*opencv.NativeByteBuffer).Len, true)
	engine.RegisterMethod("opencv.apply", "OpenCV CLAHE.Apply", (*opencv.CLAHE).Apply, true)
	return nil
}

// GetModule 返回模块实例。
func GetModule() model.Module { return &OpencvModule{} }
