//go:build android && cgo

package opencv

import (
	autogoopencv "github.com/Dasongzi1366/AutoGo/opencv"
	"github.com/ZingYao/autogo_scriptengine/lua_engine/model"
)

// OpencvModule 在 Android CGO 环境下把 Lua VM 入口桥接到真实 AutoGo/opencv。
type OpencvModule struct{}

// New 创建 opencv Lua VM 模块实例。
func New() *OpencvModule { return &OpencvModule{} }

// Name 返回模块名。
func (m *OpencvModule) Name() string { return "opencv" }

// IsAvailable 返回当前构建环境下模块是否可用。
func (m *OpencvModule) IsAvailable() bool { return true }

// Register 注册 AutoGo opencv 的真实导出方法到 Lua VM。
func (m *OpencvModule) Register(engine model.Engine) error {
	engine.RegisterMethod("opencv.newPoint2f", "OpenCV.NewPoint2f", autogoopencv.NewPoint2f, true)
	engine.RegisterMethod("opencv.newMat", "OpenCV.NewMat", autogoopencv.NewMat, true)
	engine.RegisterMethod("opencv.newMatFromCMat", "OpenCV.NewMatFromCMat", autogoopencv.NewMatFromCMat, true)
	engine.RegisterMethod("opencv.newMatWithSize", "OpenCV.NewMatWithSize", autogoopencv.NewMatWithSize, true)
	engine.RegisterMethod("opencv.newMatWithSizes", "OpenCV.NewMatWithSizes", autogoopencv.NewMatWithSizes, true)
	engine.RegisterMethod("opencv.newMatWithSizesWithScalar", "OpenCV.NewMatWithSizesWithScalar", autogoopencv.NewMatWithSizesWithScalar, true)
	engine.RegisterMethod("opencv.newMatWithSizesFromBytes", "OpenCV.NewMatWithSizesFromBytes", autogoopencv.NewMatWithSizesFromBytes, true)
	engine.RegisterMethod("opencv.newMatFromScalar", "OpenCV.NewMatFromScalar", autogoopencv.NewMatFromScalar, true)
	engine.RegisterMethod("opencv.newMatWithSizeFromScalar", "OpenCV.NewMatWithSizeFromScalar", autogoopencv.NewMatWithSizeFromScalar, true)
	engine.RegisterMethod("opencv.newMatFromBytes", "OpenCV.NewMatFromBytes", autogoopencv.NewMatFromBytes, true)
	engine.RegisterMethod("opencv.eye", "OpenCV.Eye", autogoopencv.Eye, true)
	engine.RegisterMethod("opencv.zeros", "OpenCV.Zeros", autogoopencv.Zeros, true)
	engine.RegisterMethod("opencv.ones", "OpenCV.Ones", autogoopencv.Ones, true)
	engine.RegisterMethod("opencv.lUT", "OpenCV.LUT", autogoopencv.LUT, true)
	engine.RegisterMethod("opencv.absDiff", "OpenCV.AbsDiff", autogoopencv.AbsDiff, true)
	engine.RegisterMethod("opencv.add", "OpenCV.Add", autogoopencv.Add, true)
	engine.RegisterMethod("opencv.addWeighted", "OpenCV.AddWeighted", autogoopencv.AddWeighted, true)
	engine.RegisterMethod("opencv.bitwiseAnd", "OpenCV.BitwiseAnd", autogoopencv.BitwiseAnd, true)
	engine.RegisterMethod("opencv.bitwiseAndWithMask", "OpenCV.BitwiseAndWithMask", autogoopencv.BitwiseAndWithMask, true)
	engine.RegisterMethod("opencv.bitwiseNot", "OpenCV.BitwiseNot", autogoopencv.BitwiseNot, true)
	engine.RegisterMethod("opencv.bitwiseNotWithMask", "OpenCV.BitwiseNotWithMask", autogoopencv.BitwiseNotWithMask, true)
	engine.RegisterMethod("opencv.bitwiseOr", "OpenCV.BitwiseOr", autogoopencv.BitwiseOr, true)
	engine.RegisterMethod("opencv.bitwiseOrWithMask", "OpenCV.BitwiseOrWithMask", autogoopencv.BitwiseOrWithMask, true)
	engine.RegisterMethod("opencv.bitwiseXor", "OpenCV.BitwiseXor", autogoopencv.BitwiseXor, true)
	engine.RegisterMethod("opencv.bitwiseXorWithMask", "OpenCV.BitwiseXorWithMask", autogoopencv.BitwiseXorWithMask, true)
	engine.RegisterMethod("opencv.batchDistance", "OpenCV.BatchDistance", autogoopencv.BatchDistance, true)
	engine.RegisterMethod("opencv.borderInterpolate", "OpenCV.BorderInterpolate", autogoopencv.BorderInterpolate, true)
	engine.RegisterMethod("opencv.calcCovarMatrix", "OpenCV.CalcCovarMatrix", autogoopencv.CalcCovarMatrix, true)
	engine.RegisterMethod("opencv.cartToPolar", "OpenCV.CartToPolar", autogoopencv.CartToPolar, true)
	engine.RegisterMethod("opencv.checkRange", "OpenCV.CheckRange", autogoopencv.CheckRange, true)
	engine.RegisterMethod("opencv.compare", "OpenCV.Compare", autogoopencv.Compare, true)
	engine.RegisterMethod("opencv.countNonZero", "OpenCV.CountNonZero", autogoopencv.CountNonZero, true)
	engine.RegisterMethod("opencv.completeSymm", "OpenCV.CompleteSymm", autogoopencv.CompleteSymm, true)
	engine.RegisterMethod("opencv.convertScaleAbs", "OpenCV.ConvertScaleAbs", autogoopencv.ConvertScaleAbs, true)
	engine.RegisterMethod("opencv.copyMakeBorder", "OpenCV.CopyMakeBorder", autogoopencv.CopyMakeBorder, true)
	engine.RegisterMethod("opencv.dCT", "OpenCV.DCT", autogoopencv.DCT, true)
	engine.RegisterMethod("opencv.determinant", "OpenCV.Determinant", autogoopencv.Determinant, true)
	engine.RegisterMethod("opencv.dFT", "OpenCV.DFT", autogoopencv.DFT, true)
	engine.RegisterMethod("opencv.divide", "OpenCV.Divide", autogoopencv.Divide, true)
	engine.RegisterMethod("opencv.eigen", "OpenCV.Eigen", autogoopencv.Eigen, true)
	engine.RegisterMethod("opencv.eigenNonSymmetric", "OpenCV.EigenNonSymmetric", autogoopencv.EigenNonSymmetric, true)
	engine.RegisterMethod("opencv.pCABackProject", "OpenCV.PCABackProject", autogoopencv.PCABackProject, true)
	engine.RegisterMethod("opencv.pCACompute", "OpenCV.PCACompute", autogoopencv.PCACompute, true)
	engine.RegisterMethod("opencv.pCAProject", "OpenCV.PCAProject", autogoopencv.PCAProject, true)
	engine.RegisterMethod("opencv.pSNR", "OpenCV.PSNR", autogoopencv.PSNR, true)
	engine.RegisterMethod("opencv.sVBackSubst", "OpenCV.SVBackSubst", autogoopencv.SVBackSubst, true)
	engine.RegisterMethod("opencv.sVDecomp", "OpenCV.SVDecomp", autogoopencv.SVDecomp, true)
	engine.RegisterMethod("opencv.exp", "OpenCV.Exp", autogoopencv.Exp, true)
	engine.RegisterMethod("opencv.extractChannel", "OpenCV.ExtractChannel", autogoopencv.ExtractChannel, true)
	engine.RegisterMethod("opencv.findNonZero", "OpenCV.FindNonZero", autogoopencv.FindNonZero, true)
	engine.RegisterMethod("opencv.flip", "OpenCV.Flip", autogoopencv.Flip, true)
	engine.RegisterMethod("opencv.gemm", "OpenCV.Gemm", autogoopencv.Gemm, true)
	engine.RegisterMethod("opencv.getOptimalDFTSize", "OpenCV.GetOptimalDFTSize", autogoopencv.GetOptimalDFTSize, true)
	engine.RegisterMethod("opencv.hconcat", "OpenCV.Hconcat", autogoopencv.Hconcat, true)
	engine.RegisterMethod("opencv.vconcat", "OpenCV.Vconcat", autogoopencv.Vconcat, true)
	engine.RegisterMethod("opencv.rotate", "OpenCV.Rotate", autogoopencv.Rotate, true)
	engine.RegisterMethod("opencv.iDCT", "OpenCV.IDCT", autogoopencv.IDCT, true)
	engine.RegisterMethod("opencv.iDFT", "OpenCV.IDFT", autogoopencv.IDFT, true)
	engine.RegisterMethod("opencv.inRange", "OpenCV.InRange", autogoopencv.InRange, true)
	engine.RegisterMethod("opencv.inRangeWithScalar", "OpenCV.InRangeWithScalar", autogoopencv.InRangeWithScalar, true)
	engine.RegisterMethod("opencv.insertChannel", "OpenCV.InsertChannel", autogoopencv.InsertChannel, true)
	engine.RegisterMethod("opencv.invert", "OpenCV.Invert", autogoopencv.Invert, true)
	engine.RegisterMethod("opencv.kMeans", "OpenCV.KMeans", autogoopencv.KMeans, true)
	engine.RegisterMethod("opencv.kMeansPoints", "OpenCV.KMeansPoints", autogoopencv.KMeansPoints, true)
	engine.RegisterMethod("opencv.log", "OpenCV.Log", autogoopencv.Log, true)
	engine.RegisterMethod("opencv.magnitude", "OpenCV.Magnitude", autogoopencv.Magnitude, true)
	engine.RegisterMethod("opencv.mahalanobis", "OpenCV.Mahalanobis", autogoopencv.Mahalanobis, true)
	engine.RegisterMethod("opencv.mulTransposed", "OpenCV.MulTransposed", autogoopencv.MulTransposed, true)
	engine.RegisterMethod("opencv.max", "OpenCV.Max", autogoopencv.Max, true)
	engine.RegisterMethod("opencv.meanStdDev", "OpenCV.MeanStdDev", autogoopencv.MeanStdDev, true)
	engine.RegisterMethod("opencv.merge", "OpenCV.Merge", autogoopencv.Merge, true)
	engine.RegisterMethod("opencv.min", "OpenCV.Min", autogoopencv.Min, true)
	engine.RegisterMethod("opencv.minMaxIdx", "OpenCV.MinMaxIdx", autogoopencv.MinMaxIdx, true)
	engine.RegisterMethod("opencv.minMaxLoc", "OpenCV.MinMaxLoc", autogoopencv.MinMaxLoc, true)
	engine.RegisterMethod("opencv.minMaxLocWithMask", "OpenCV.MinMaxLocWithMask", autogoopencv.MinMaxLocWithMask, true)
	engine.RegisterMethod("opencv.mixChannels", "OpenCV.MixChannels", autogoopencv.MixChannels, true)
	engine.RegisterMethod("opencv.mulSpectrums", "OpenCV.MulSpectrums", autogoopencv.MulSpectrums, true)
	engine.RegisterMethod("opencv.multiply", "OpenCV.Multiply", autogoopencv.Multiply, true)
	engine.RegisterMethod("opencv.multiplyWithParams", "OpenCV.MultiplyWithParams", autogoopencv.MultiplyWithParams, true)
	engine.RegisterMethod("opencv.normalize", "OpenCV.Normalize", autogoopencv.Normalize, true)
	engine.RegisterMethod("opencv.norm", "OpenCV.Norm", autogoopencv.Norm, true)
	engine.RegisterMethod("opencv.normWithMats", "OpenCV.NormWithMats", autogoopencv.NormWithMats, true)
	engine.RegisterMethod("opencv.perspectiveTransform", "OpenCV.PerspectiveTransform", autogoopencv.PerspectiveTransform, true)
	engine.RegisterMethod("opencv.solve", "OpenCV.Solve", autogoopencv.Solve, true)
	engine.RegisterMethod("opencv.solveCubic", "OpenCV.SolveCubic", autogoopencv.SolveCubic, true)
	engine.RegisterMethod("opencv.solvePoly", "OpenCV.SolvePoly", autogoopencv.SolvePoly, true)
	engine.RegisterMethod("opencv.reduce", "OpenCV.Reduce", autogoopencv.Reduce, true)
	engine.RegisterMethod("opencv.reduceArgMax", "OpenCV.ReduceArgMax", autogoopencv.ReduceArgMax, true)
	engine.RegisterMethod("opencv.reduceArgMin", "OpenCV.ReduceArgMin", autogoopencv.ReduceArgMin, true)
	engine.RegisterMethod("opencv.repeat", "OpenCV.Repeat", autogoopencv.Repeat, true)
	engine.RegisterMethod("opencv.scaleAdd", "OpenCV.ScaleAdd", autogoopencv.ScaleAdd, true)
	engine.RegisterMethod("opencv.setIdentity", "OpenCV.SetIdentity", autogoopencv.SetIdentity, true)
	engine.RegisterMethod("opencv.sort", "OpenCV.Sort", autogoopencv.Sort, true)
	engine.RegisterMethod("opencv.sortIdx", "OpenCV.SortIdx", autogoopencv.SortIdx, true)
	engine.RegisterMethod("opencv.split", "OpenCV.Split", autogoopencv.Split, true)
	engine.RegisterMethod("opencv.subtract", "OpenCV.Subtract", autogoopencv.Subtract, true)
	engine.RegisterMethod("opencv.trace", "OpenCV.Trace", autogoopencv.Trace, true)
	engine.RegisterMethod("opencv.transform", "OpenCV.Transform", autogoopencv.Transform, true)
	engine.RegisterMethod("opencv.transpose", "OpenCV.Transpose", autogoopencv.Transpose, true)
	engine.RegisterMethod("opencv.transposeND", "OpenCV.TransposeND", autogoopencv.TransposeND, true)
	engine.RegisterMethod("opencv.pow", "OpenCV.Pow", autogoopencv.Pow, true)
	engine.RegisterMethod("opencv.polarToCart", "OpenCV.PolarToCart", autogoopencv.PolarToCart, true)
	engine.RegisterMethod("opencv.phase", "OpenCV.Phase", autogoopencv.Phase, true)
	engine.RegisterMethod("opencv.newTermCriteria", "OpenCV.NewTermCriteria", autogoopencv.NewTermCriteria, true)
	engine.RegisterMethod("opencv.newScalar", "OpenCV.NewScalar", autogoopencv.NewScalar, true)
	engine.RegisterMethod("opencv.newPointVector", "OpenCV.NewPointVector", autogoopencv.NewPointVector, true)
	engine.RegisterMethod("opencv.newPointVectorFromPoints", "OpenCV.NewPointVectorFromPoints", autogoopencv.NewPointVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPointVectorFromMat", "OpenCV.NewPointVectorFromMat", autogoopencv.NewPointVectorFromMat, true)
	engine.RegisterMethod("opencv.newPointsVector", "OpenCV.NewPointsVector", autogoopencv.NewPointsVector, true)
	engine.RegisterMethod("opencv.newPointsVectorFromPoints", "OpenCV.NewPointsVectorFromPoints", autogoopencv.NewPointsVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint2fVector", "OpenCV.NewPoint2fVector", autogoopencv.NewPoint2fVector, true)
	engine.RegisterMethod("opencv.newPoint2fVectorFromPoints", "OpenCV.NewPoint2fVectorFromPoints", autogoopencv.NewPoint2fVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint2fVectorFromMat", "OpenCV.NewPoint2fVectorFromMat", autogoopencv.NewPoint2fVectorFromMat, true)
	engine.RegisterMethod("opencv.getTickCount", "OpenCV.GetTickCount", autogoopencv.GetTickCount, true)
	engine.RegisterMethod("opencv.getTickFrequency", "OpenCV.GetTickFrequency", autogoopencv.GetTickFrequency, true)
	engine.RegisterMethod("opencv.theRNG", "OpenCV.TheRNG", autogoopencv.TheRNG, true)
	engine.RegisterMethod("opencv.setRNGSeed", "OpenCV.SetRNGSeed", autogoopencv.SetRNGSeed, true)
	engine.RegisterMethod("opencv.randN", "OpenCV.RandN", autogoopencv.RandN, true)
	engine.RegisterMethod("opencv.randShuffle", "OpenCV.RandShuffle", autogoopencv.RandShuffle, true)
	engine.RegisterMethod("opencv.randShuffleWithParams", "OpenCV.RandShuffleWithParams", autogoopencv.RandShuffleWithParams, true)
	engine.RegisterMethod("opencv.randU", "OpenCV.RandU", autogoopencv.RandU, true)
	engine.RegisterMethod("opencv.newPoints2fVector", "OpenCV.NewPoints2fVector", autogoopencv.NewPoints2fVector, true)
	engine.RegisterMethod("opencv.newPoints2fVectorFromPoints", "OpenCV.NewPoints2fVectorFromPoints", autogoopencv.NewPoints2fVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint3f", "OpenCV.NewPoint3f", autogoopencv.NewPoint3f, true)
	engine.RegisterMethod("opencv.newPoint3fVector", "OpenCV.NewPoint3fVector", autogoopencv.NewPoint3fVector, true)
	engine.RegisterMethod("opencv.newPoint3fVectorFromPoints", "OpenCV.NewPoint3fVectorFromPoints", autogoopencv.NewPoint3fVectorFromPoints, true)
	engine.RegisterMethod("opencv.newPoint3fVectorFromMat", "OpenCV.NewPoint3fVectorFromMat", autogoopencv.NewPoint3fVectorFromMat, true)
	engine.RegisterMethod("opencv.newPoints3fVector", "OpenCV.NewPoints3fVector", autogoopencv.NewPoints3fVector, true)
	engine.RegisterMethod("opencv.newPoints3fVectorFromPoints", "OpenCV.NewPoints3fVectorFromPoints", autogoopencv.NewPoints3fVectorFromPoints, true)
	engine.RegisterMethod("opencv.setNumThreads", "OpenCV.SetNumThreads", autogoopencv.SetNumThreads, true)
	engine.RegisterMethod("opencv.getNumThreads", "OpenCV.GetNumThreads", autogoopencv.GetNumThreads, true)
	engine.RegisterMethod("opencv.newRotatedRect", "OpenCV.NewRotatedRect", autogoopencv.NewRotatedRect, true)
	engine.RegisterMethod("opencv.newRotatedRect2f", "OpenCV.NewRotatedRect2f", autogoopencv.NewRotatedRect2f, true)
	engine.RegisterMethod("opencv.lastExceptionError", "OpenCV.LastExceptionError", autogoopencv.LastExceptionError, true)
	engine.RegisterMethod("opencv.getLastExceptionMessage", "OpenCV.GetLastExceptionMessage", autogoopencv.GetLastExceptionMessage, true)
	engine.RegisterMethod("opencv.clearLastException", "OpenCV.ClearLastException", autogoopencv.ClearLastException, true)
	engine.RegisterMethod("opencv.getLastException", "OpenCV.GetLastException", autogoopencv.GetLastException, true)
	engine.RegisterMethod("opencv.openCVResult", "OpenCV.OpenCVResult", autogoopencv.OpenCVResult, true)
	engine.RegisterMethod("opencv.iMRead", "OpenCV.IMRead", autogoopencv.IMRead, true)
	engine.RegisterMethod("opencv.iMReadMulti", "OpenCV.IMReadMulti", autogoopencv.IMReadMulti, true)
	engine.RegisterMethod("opencv.iMReadMulti_WithParams", "OpenCV.IMReadMulti_WithParams", autogoopencv.IMReadMulti_WithParams, true)
	engine.RegisterMethod("opencv.iMWrite", "OpenCV.IMWrite", autogoopencv.IMWrite, true)
	engine.RegisterMethod("opencv.iMWriteWithParams", "OpenCV.IMWriteWithParams", autogoopencv.IMWriteWithParams, true)
	engine.RegisterMethod("opencv.iMEncode", "OpenCV.IMEncode", autogoopencv.IMEncode, true)
	engine.RegisterMethod("opencv.iMEncodeWithParams", "OpenCV.IMEncodeWithParams", autogoopencv.IMEncodeWithParams, true)
	engine.RegisterMethod("opencv.iMDecode", "OpenCV.IMDecode", autogoopencv.IMDecode, true)
	engine.RegisterMethod("opencv.iMDecodeIntoMat", "OpenCV.IMDecodeIntoMat", autogoopencv.IMDecodeIntoMat, true)
	engine.RegisterMethod("opencv.arcLength", "OpenCV.ArcLength", autogoopencv.ArcLength, true)
	engine.RegisterMethod("opencv.approxPolyDP", "OpenCV.ApproxPolyDP", autogoopencv.ApproxPolyDP, true)
	engine.RegisterMethod("opencv.convexHull", "OpenCV.ConvexHull", autogoopencv.ConvexHull, true)
	engine.RegisterMethod("opencv.convexityDefects", "OpenCV.ConvexityDefects", autogoopencv.ConvexityDefects, true)
	engine.RegisterMethod("opencv.cvtColor", "OpenCV.CvtColor", autogoopencv.CvtColor, true)
	engine.RegisterMethod("opencv.demosaicing", "OpenCV.Demosaicing", autogoopencv.Demosaicing, true)
	engine.RegisterMethod("opencv.equalizeHist", "OpenCV.EqualizeHist", autogoopencv.EqualizeHist, true)
	engine.RegisterMethod("opencv.calcHist", "OpenCV.CalcHist", autogoopencv.CalcHist, true)
	engine.RegisterMethod("opencv.calcBackProject", "OpenCV.CalcBackProject", autogoopencv.CalcBackProject, true)
	engine.RegisterMethod("opencv.compareHist", "OpenCV.CompareHist", autogoopencv.CompareHist, true)
	engine.RegisterMethod("opencv.eMD", "OpenCV.EMD", autogoopencv.EMD, true)
	engine.RegisterMethod("opencv.clipLine", "OpenCV.ClipLine", autogoopencv.ClipLine, true)
	engine.RegisterMethod("opencv.bilateralFilter", "OpenCV.BilateralFilter", autogoopencv.BilateralFilter, true)
	engine.RegisterMethod("opencv.blur", "OpenCV.Blur", autogoopencv.Blur, true)
	engine.RegisterMethod("opencv.boxFilter", "OpenCV.BoxFilter", autogoopencv.BoxFilter, true)
	engine.RegisterMethod("opencv.sqBoxFilter", "OpenCV.SqBoxFilter", autogoopencv.SqBoxFilter, true)
	engine.RegisterMethod("opencv.dilate", "OpenCV.Dilate", autogoopencv.Dilate, true)
	engine.RegisterMethod("opencv.dilateWithParams", "OpenCV.DilateWithParams", autogoopencv.DilateWithParams, true)
	engine.RegisterMethod("opencv.distanceTransform", "OpenCV.DistanceTransform", autogoopencv.DistanceTransform, true)
	engine.RegisterMethod("opencv.erode", "OpenCV.Erode", autogoopencv.Erode, true)
	engine.RegisterMethod("opencv.erodeWithParams", "OpenCV.ErodeWithParams", autogoopencv.ErodeWithParams, true)
	engine.RegisterMethod("opencv.erodeWithParamsAndBorderValue", "OpenCV.ErodeWithParamsAndBorderValue", autogoopencv.ErodeWithParamsAndBorderValue, true)
	engine.RegisterMethod("opencv.boundingRect", "OpenCV.BoundingRect", autogoopencv.BoundingRect, true)
	engine.RegisterMethod("opencv.boxPoints", "OpenCV.BoxPoints", autogoopencv.BoxPoints, true)
	engine.RegisterMethod("opencv.boxPoints2f", "OpenCV.BoxPoints2f", autogoopencv.BoxPoints2f, true)
	engine.RegisterMethod("opencv.contourArea", "OpenCV.ContourArea", autogoopencv.ContourArea, true)
	engine.RegisterMethod("opencv.minAreaRect", "OpenCV.MinAreaRect", autogoopencv.MinAreaRect, true)
	engine.RegisterMethod("opencv.minAreaRect2f", "OpenCV.MinAreaRect2f", autogoopencv.MinAreaRect2f, true)
	engine.RegisterMethod("opencv.fitEllipse", "OpenCV.FitEllipse", autogoopencv.FitEllipse, true)
	engine.RegisterMethod("opencv.minEnclosingCircle", "OpenCV.MinEnclosingCircle", autogoopencv.MinEnclosingCircle, true)
	engine.RegisterMethod("opencv.findContours", "OpenCV.FindContours", autogoopencv.FindContours, true)
	engine.RegisterMethod("opencv.findContoursWithParams", "OpenCV.FindContoursWithParams", autogoopencv.FindContoursWithParams, true)
	engine.RegisterMethod("opencv.pointPolygonTest", "OpenCV.PointPolygonTest", autogoopencv.PointPolygonTest, true)
	engine.RegisterMethod("opencv.connectedComponents", "OpenCV.ConnectedComponents", autogoopencv.ConnectedComponents, true)
	engine.RegisterMethod("opencv.connectedComponentsWithParams", "OpenCV.ConnectedComponentsWithParams", autogoopencv.ConnectedComponentsWithParams, true)
	engine.RegisterMethod("opencv.connectedComponentsWithStats", "OpenCV.ConnectedComponentsWithStats", autogoopencv.ConnectedComponentsWithStats, true)
	engine.RegisterMethod("opencv.connectedComponentsWithStatsWithParams", "OpenCV.ConnectedComponentsWithStatsWithParams", autogoopencv.ConnectedComponentsWithStatsWithParams, true)
	engine.RegisterMethod("opencv.matchTemplate", "OpenCV.MatchTemplate", autogoopencv.MatchTemplate, true)
	engine.RegisterMethod("opencv.moments", "OpenCV.Moments", autogoopencv.Moments, true)
	engine.RegisterMethod("opencv.pyrDown", "OpenCV.PyrDown", autogoopencv.PyrDown, true)
	engine.RegisterMethod("opencv.pyrUp", "OpenCV.PyrUp", autogoopencv.PyrUp, true)
	engine.RegisterMethod("opencv.morphologyDefaultBorderValue", "OpenCV.MorphologyDefaultBorderValue", autogoopencv.MorphologyDefaultBorderValue, true)
	engine.RegisterMethod("opencv.morphologyEx", "OpenCV.MorphologyEx", autogoopencv.MorphologyEx, true)
	engine.RegisterMethod("opencv.morphologyExWithParams", "OpenCV.MorphologyExWithParams", autogoopencv.MorphologyExWithParams, true)
	engine.RegisterMethod("opencv.getStructuringElement", "OpenCV.GetStructuringElement", autogoopencv.GetStructuringElement, true)
	engine.RegisterMethod("opencv.gaussianBlur", "OpenCV.GaussianBlur", autogoopencv.GaussianBlur, true)
	engine.RegisterMethod("opencv.getGaussianKernel", "OpenCV.GetGaussianKernel", autogoopencv.GetGaussianKernel, true)
	engine.RegisterMethod("opencv.getGaussianKernelWithParams", "OpenCV.GetGaussianKernelWithParams", autogoopencv.GetGaussianKernelWithParams, true)
	engine.RegisterMethod("opencv.sobel", "OpenCV.Sobel", autogoopencv.Sobel, true)
	engine.RegisterMethod("opencv.spatialGradient", "OpenCV.SpatialGradient", autogoopencv.SpatialGradient, true)
	engine.RegisterMethod("opencv.laplacian", "OpenCV.Laplacian", autogoopencv.Laplacian, true)
	engine.RegisterMethod("opencv.scharr", "OpenCV.Scharr", autogoopencv.Scharr, true)
	engine.RegisterMethod("opencv.medianBlur", "OpenCV.MedianBlur", autogoopencv.MedianBlur, true)
	engine.RegisterMethod("opencv.canny", "OpenCV.Canny", autogoopencv.Canny, true)
	engine.RegisterMethod("opencv.cornerSubPix", "OpenCV.CornerSubPix", autogoopencv.CornerSubPix, true)
	engine.RegisterMethod("opencv.goodFeaturesToTrack", "OpenCV.GoodFeaturesToTrack", autogoopencv.GoodFeaturesToTrack, true)
	engine.RegisterMethod("opencv.grabCut", "OpenCV.GrabCut", autogoopencv.GrabCut, true)
	engine.RegisterMethod("opencv.houghCircles", "OpenCV.HoughCircles", autogoopencv.HoughCircles, true)
	engine.RegisterMethod("opencv.houghCirclesWithParams", "OpenCV.HoughCirclesWithParams", autogoopencv.HoughCirclesWithParams, true)
	engine.RegisterMethod("opencv.houghLines", "OpenCV.HoughLines", autogoopencv.HoughLines, true)
	engine.RegisterMethod("opencv.houghLinesP", "OpenCV.HoughLinesP", autogoopencv.HoughLinesP, true)
	engine.RegisterMethod("opencv.houghLinesPWithParams", "OpenCV.HoughLinesPWithParams", autogoopencv.HoughLinesPWithParams, true)
	engine.RegisterMethod("opencv.houghLinesPointSet", "OpenCV.HoughLinesPointSet", autogoopencv.HoughLinesPointSet, true)
	engine.RegisterMethod("opencv.integral", "OpenCV.Integral", autogoopencv.Integral, true)
	engine.RegisterMethod("opencv.threshold", "OpenCV.Threshold", autogoopencv.Threshold, true)
	engine.RegisterMethod("opencv.adaptiveThreshold", "OpenCV.AdaptiveThreshold", autogoopencv.AdaptiveThreshold, true)
	engine.RegisterMethod("opencv.arrowedLine", "OpenCV.ArrowedLine", autogoopencv.ArrowedLine, true)
	engine.RegisterMethod("opencv.circle", "OpenCV.Circle", autogoopencv.Circle, true)
	engine.RegisterMethod("opencv.circleWithParams", "OpenCV.CircleWithParams", autogoopencv.CircleWithParams, true)
	engine.RegisterMethod("opencv.ellipse", "OpenCV.Ellipse", autogoopencv.Ellipse, true)
	engine.RegisterMethod("opencv.ellipseWithParams", "OpenCV.EllipseWithParams", autogoopencv.EllipseWithParams, true)
	engine.RegisterMethod("opencv.line", "OpenCV.Line", autogoopencv.Line, true)
	engine.RegisterMethod("opencv.rectangle", "OpenCV.Rectangle", autogoopencv.Rectangle, true)
	engine.RegisterMethod("opencv.rectangleWithParams", "OpenCV.RectangleWithParams", autogoopencv.RectangleWithParams, true)
	engine.RegisterMethod("opencv.fillPoly", "OpenCV.FillPoly", autogoopencv.FillPoly, true)
	engine.RegisterMethod("opencv.fillPolyWithParams", "OpenCV.FillPolyWithParams", autogoopencv.FillPolyWithParams, true)
	engine.RegisterMethod("opencv.polylines", "OpenCV.Polylines", autogoopencv.Polylines, true)
	engine.RegisterMethod("opencv.getTextSize", "OpenCV.GetTextSize", autogoopencv.GetTextSize, true)
	engine.RegisterMethod("opencv.getTextSizeWithBaseline", "OpenCV.GetTextSizeWithBaseline", autogoopencv.GetTextSizeWithBaseline, true)
	engine.RegisterMethod("opencv.putText", "OpenCV.PutText", autogoopencv.PutText, true)
	engine.RegisterMethod("opencv.putTextWithParams", "OpenCV.PutTextWithParams", autogoopencv.PutTextWithParams, true)
	engine.RegisterMethod("opencv.resize", "OpenCV.Resize", autogoopencv.Resize, true)
	engine.RegisterMethod("opencv.getRectSubPix", "OpenCV.GetRectSubPix", autogoopencv.GetRectSubPix, true)
	engine.RegisterMethod("opencv.getRotationMatrix2D", "OpenCV.GetRotationMatrix2D", autogoopencv.GetRotationMatrix2D, true)
	engine.RegisterMethod("opencv.warpAffine", "OpenCV.WarpAffine", autogoopencv.WarpAffine, true)
	engine.RegisterMethod("opencv.warpAffineWithParams", "OpenCV.WarpAffineWithParams", autogoopencv.WarpAffineWithParams, true)
	engine.RegisterMethod("opencv.warpPerspective", "OpenCV.WarpPerspective", autogoopencv.WarpPerspective, true)
	engine.RegisterMethod("opencv.warpPerspectiveWithParams", "OpenCV.WarpPerspectiveWithParams", autogoopencv.WarpPerspectiveWithParams, true)
	engine.RegisterMethod("opencv.watershed", "OpenCV.Watershed", autogoopencv.Watershed, true)
	engine.RegisterMethod("opencv.applyColorMap", "OpenCV.ApplyColorMap", autogoopencv.ApplyColorMap, true)
	engine.RegisterMethod("opencv.applyCustomColorMap", "OpenCV.ApplyCustomColorMap", autogoopencv.ApplyCustomColorMap, true)
	engine.RegisterMethod("opencv.getPerspectiveTransform", "OpenCV.GetPerspectiveTransform", autogoopencv.GetPerspectiveTransform, true)
	engine.RegisterMethod("opencv.getPerspectiveTransform2f", "OpenCV.GetPerspectiveTransform2f", autogoopencv.GetPerspectiveTransform2f, true)
	engine.RegisterMethod("opencv.getAffineTransform", "OpenCV.GetAffineTransform", autogoopencv.GetAffineTransform, true)
	engine.RegisterMethod("opencv.getAffineTransform2f", "OpenCV.GetAffineTransform2f", autogoopencv.GetAffineTransform2f, true)
	engine.RegisterMethod("opencv.drawContours", "OpenCV.DrawContours", autogoopencv.DrawContours, true)
	engine.RegisterMethod("opencv.drawContoursWithParams", "OpenCV.DrawContoursWithParams", autogoopencv.DrawContoursWithParams, true)
	engine.RegisterMethod("opencv.remap", "OpenCV.Remap", autogoopencv.Remap, true)
	engine.RegisterMethod("opencv.filter2D", "OpenCV.Filter2D", autogoopencv.Filter2D, true)
	engine.RegisterMethod("opencv.sepFilter2D", "OpenCV.SepFilter2D", autogoopencv.SepFilter2D, true)
	engine.RegisterMethod("opencv.logPolar", "OpenCV.LogPolar", autogoopencv.LogPolar, true)
	engine.RegisterMethod("opencv.linearPolar", "OpenCV.LinearPolar", autogoopencv.LinearPolar, true)
	engine.RegisterMethod("opencv.fitLine", "OpenCV.FitLine", autogoopencv.FitLine, true)
	engine.RegisterMethod("opencv.matchShapes", "OpenCV.MatchShapes", autogoopencv.MatchShapes, true)
	engine.RegisterMethod("opencv.newCLAHE", "OpenCV.NewCLAHE", autogoopencv.NewCLAHE, true)
	engine.RegisterMethod("opencv.newCLAHEWithParams", "OpenCV.NewCLAHEWithParams", autogoopencv.NewCLAHEWithParams, true)
	engine.RegisterMethod("opencv.invertAffineTransform", "OpenCV.InvertAffineTransform", autogoopencv.InvertAffineTransform, true)
	engine.RegisterMethod("opencv.phaseCorrelate", "OpenCV.PhaseCorrelate", autogoopencv.PhaseCorrelate, true)
	engine.RegisterMethod("opencv.createHanningWindow", "OpenCV.CreateHanningWindow", autogoopencv.CreateHanningWindow, true)
	engine.RegisterMethod("opencv.imageToMatRGBA", "OpenCV.ImageToMatRGBA", autogoopencv.ImageToMatRGBA, true)
	engine.RegisterMethod("opencv.imageToMatRGB", "OpenCV.ImageToMatRGB", autogoopencv.ImageToMatRGB, true)
	engine.RegisterMethod("opencv.imageGrayToMatGray", "OpenCV.ImageGrayToMatGray", autogoopencv.ImageGrayToMatGray, true)
	engine.RegisterMethod("opencv.accumulate", "OpenCV.Accumulate", autogoopencv.Accumulate, true)
	engine.RegisterMethod("opencv.accumulateWithMask", "OpenCV.AccumulateWithMask", autogoopencv.AccumulateWithMask, true)
	engine.RegisterMethod("opencv.accumulateSquare", "OpenCV.AccumulateSquare", autogoopencv.AccumulateSquare, true)
	engine.RegisterMethod("opencv.accumulateSquareWithMask", "OpenCV.AccumulateSquareWithMask", autogoopencv.AccumulateSquareWithMask, true)
	engine.RegisterMethod("opencv.accumulateProduct", "OpenCV.AccumulateProduct", autogoopencv.AccumulateProduct, true)
	engine.RegisterMethod("opencv.accumulateProductWithMask", "OpenCV.AccumulateProductWithMask", autogoopencv.AccumulateProductWithMask, true)
	engine.RegisterMethod("opencv.accumulatedWeighted", "OpenCV.AccumulatedWeighted", autogoopencv.AccumulatedWeighted, true)
	engine.RegisterMethod("opencv.accumulatedWeightedWithMask", "OpenCV.AccumulatedWeightedWithMask", autogoopencv.AccumulatedWeightedWithMask, true)
	engine.RegisterMethod("opencv.findImage", "OpenCV.FindImage", autogoopencv.FindImage, true)
	engine.RegisterMethod("opencv.findImageAll", "OpenCV.FindImageAll", autogoopencv.FindImageAll, true)
	engine.RegisterMethod("opencv.close", "OpenCV Mat.Close", (*opencv.Mat).Close, true)
	engine.RegisterMethod("opencv.fromPtr", "OpenCV Mat.FromPtr", (*opencv.Mat).FromPtr, true)
	engine.RegisterMethod("opencv.ptr", "OpenCV Mat.Ptr", (*opencv.Mat).Ptr, true)
	engine.RegisterMethod("opencv.empty", "OpenCV Mat.Empty", (*opencv.Mat).Empty, true)
	engine.RegisterMethod("opencv.closed", "OpenCV Mat.Closed", (*opencv.Mat).Closed, true)
	engine.RegisterMethod("opencv.isContinuous", "OpenCV Mat.IsContinuous", (*opencv.Mat).IsContinuous, true)
	engine.RegisterMethod("opencv.inv", "OpenCV Mat.Inv", (*opencv.Mat).Inv, true)
	engine.RegisterMethod("opencv.col", "OpenCV Mat.Col", (*opencv.Mat).Col, true)
	engine.RegisterMethod("opencv.row", "OpenCV Mat.Row", (*opencv.Mat).Row, true)
	engine.RegisterMethod("opencv.clone", "OpenCV Mat.Clone", (*opencv.Mat).Clone, true)
	engine.RegisterMethod("opencv.copyTo", "OpenCV Mat.CopyTo", (*opencv.Mat).CopyTo, true)
	engine.RegisterMethod("opencv.copyToWithMask", "OpenCV Mat.CopyToWithMask", (*opencv.Mat).CopyToWithMask, true)
	engine.RegisterMethod("opencv.convertTo", "OpenCV Mat.ConvertTo", (*opencv.Mat).ConvertTo, true)
	engine.RegisterMethod("opencv.convertToWithParams", "OpenCV Mat.ConvertToWithParams", (*opencv.Mat).ConvertToWithParams, true)
	engine.RegisterMethod("opencv.total", "OpenCV Mat.Total", (*opencv.Mat).Total, true)
	engine.RegisterMethod("opencv.size", "OpenCV Mat.Size", (*opencv.Mat).Size, true)
	engine.RegisterMethod("opencv.toBytes", "OpenCV Mat.ToBytes", (*opencv.Mat).ToBytes, true)
	engine.RegisterMethod("opencv.dataPtrUint8", "OpenCV Mat.DataPtrUint8", (*opencv.Mat).DataPtrUint8, true)
	engine.RegisterMethod("opencv.dataPtrInt8", "OpenCV Mat.DataPtrInt8", (*opencv.Mat).DataPtrInt8, true)
	engine.RegisterMethod("opencv.dataPtrUint16", "OpenCV Mat.DataPtrUint16", (*opencv.Mat).DataPtrUint16, true)
	engine.RegisterMethod("opencv.dataPtrInt16", "OpenCV Mat.DataPtrInt16", (*opencv.Mat).DataPtrInt16, true)
	engine.RegisterMethod("opencv.dataPtrFloat32", "OpenCV Mat.DataPtrFloat32", (*opencv.Mat).DataPtrFloat32, true)
	engine.RegisterMethod("opencv.dataPtrFloat64", "OpenCV Mat.DataPtrFloat64", (*opencv.Mat).DataPtrFloat64, true)
	engine.RegisterMethod("opencv.region", "OpenCV Mat.Region", (*opencv.Mat).Region, true)
	engine.RegisterMethod("opencv.reshape", "OpenCV Mat.Reshape", (*opencv.Mat).Reshape, true)
	engine.RegisterMethod("opencv.convertFp16", "OpenCV Mat.ConvertFp16", (*opencv.Mat).ConvertFp16, true)
	engine.RegisterMethod("opencv.mean", "OpenCV Mat.Mean", (*opencv.Mat).Mean, true)
	engine.RegisterMethod("opencv.meanWithMask", "OpenCV Mat.MeanWithMask", (*opencv.Mat).MeanWithMask, true)
	engine.RegisterMethod("opencv.sqrt", "OpenCV Mat.Sqrt", (*opencv.Mat).Sqrt, true)
	engine.RegisterMethod("opencv.sum", "OpenCV Mat.Sum", (*opencv.Mat).Sum, true)
	engine.RegisterMethod("opencv.patchNaNs", "OpenCV Mat.PatchNaNs", (*opencv.Mat).PatchNaNs, true)
	engine.RegisterMethod("opencv.rows", "OpenCV Mat.Rows", (*opencv.Mat).Rows, true)
	engine.RegisterMethod("opencv.cols", "OpenCV Mat.Cols", (*opencv.Mat).Cols, true)
	engine.RegisterMethod("opencv.channels", "OpenCV Mat.Channels", (*opencv.Mat).Channels, true)
	engine.RegisterMethod("opencv.type", "OpenCV Mat.Type", (*opencv.Mat).Type, true)
	engine.RegisterMethod("opencv.step", "OpenCV Mat.Step", (*opencv.Mat).Step, true)
	engine.RegisterMethod("opencv.elemSize", "OpenCV Mat.ElemSize", (*opencv.Mat).ElemSize, true)
	engine.RegisterMethod("opencv.getUCharAt", "OpenCV Mat.GetUCharAt", (*opencv.Mat).GetUCharAt, true)
	engine.RegisterMethod("opencv.getUCharAt3", "OpenCV Mat.GetUCharAt3", (*opencv.Mat).GetUCharAt3, true)
	engine.RegisterMethod("opencv.getSCharAt", "OpenCV Mat.GetSCharAt", (*opencv.Mat).GetSCharAt, true)
	engine.RegisterMethod("opencv.getSCharAt3", "OpenCV Mat.GetSCharAt3", (*opencv.Mat).GetSCharAt3, true)
	engine.RegisterMethod("opencv.getShortAt", "OpenCV Mat.GetShortAt", (*opencv.Mat).GetShortAt, true)
	engine.RegisterMethod("opencv.getShortAt3", "OpenCV Mat.GetShortAt3", (*opencv.Mat).GetShortAt3, true)
	engine.RegisterMethod("opencv.getIntAt", "OpenCV Mat.GetIntAt", (*opencv.Mat).GetIntAt, true)
	engine.RegisterMethod("opencv.getIntAt3", "OpenCV Mat.GetIntAt3", (*opencv.Mat).GetIntAt3, true)
	engine.RegisterMethod("opencv.getFloatAt", "OpenCV Mat.GetFloatAt", (*opencv.Mat).GetFloatAt, true)
	engine.RegisterMethod("opencv.getFloatAt3", "OpenCV Mat.GetFloatAt3", (*opencv.Mat).GetFloatAt3, true)
	engine.RegisterMethod("opencv.getDoubleAt", "OpenCV Mat.GetDoubleAt", (*opencv.Mat).GetDoubleAt, true)
	engine.RegisterMethod("opencv.getDoubleAt3", "OpenCV Mat.GetDoubleAt3", (*opencv.Mat).GetDoubleAt3, true)
	engine.RegisterMethod("opencv.setTo", "OpenCV Mat.SetTo", (*opencv.Mat).SetTo, true)
	engine.RegisterMethod("opencv.setUCharAt", "OpenCV Mat.SetUCharAt", (*opencv.Mat).SetUCharAt, true)
	engine.RegisterMethod("opencv.setUCharAt3", "OpenCV Mat.SetUCharAt3", (*opencv.Mat).SetUCharAt3, true)
	engine.RegisterMethod("opencv.setSCharAt", "OpenCV Mat.SetSCharAt", (*opencv.Mat).SetSCharAt, true)
	engine.RegisterMethod("opencv.setSCharAt3", "OpenCV Mat.SetSCharAt3", (*opencv.Mat).SetSCharAt3, true)
	engine.RegisterMethod("opencv.setShortAt", "OpenCV Mat.SetShortAt", (*opencv.Mat).SetShortAt, true)
	engine.RegisterMethod("opencv.setShortAt3", "OpenCV Mat.SetShortAt3", (*opencv.Mat).SetShortAt3, true)
	engine.RegisterMethod("opencv.setIntAt", "OpenCV Mat.SetIntAt", (*opencv.Mat).SetIntAt, true)
	engine.RegisterMethod("opencv.setIntAt3", "OpenCV Mat.SetIntAt3", (*opencv.Mat).SetIntAt3, true)
	engine.RegisterMethod("opencv.setFloatAt", "OpenCV Mat.SetFloatAt", (*opencv.Mat).SetFloatAt, true)
	engine.RegisterMethod("opencv.setFloatAt3", "OpenCV Mat.SetFloatAt3", (*opencv.Mat).SetFloatAt3, true)
	engine.RegisterMethod("opencv.setDoubleAt", "OpenCV Mat.SetDoubleAt", (*opencv.Mat).SetDoubleAt, true)
	engine.RegisterMethod("opencv.setDoubleAt3", "OpenCV Mat.SetDoubleAt3", (*opencv.Mat).SetDoubleAt3, true)
	engine.RegisterMethod("opencv.addUChar", "OpenCV Mat.AddUChar", (*opencv.Mat).AddUChar, true)
	engine.RegisterMethod("opencv.subtractUChar", "OpenCV Mat.SubtractUChar", (*opencv.Mat).SubtractUChar, true)
	engine.RegisterMethod("opencv.multiplyUChar", "OpenCV Mat.MultiplyUChar", (*opencv.Mat).MultiplyUChar, true)
	engine.RegisterMethod("opencv.divideUChar", "OpenCV Mat.DivideUChar", (*opencv.Mat).DivideUChar, true)
	engine.RegisterMethod("opencv.addFloat", "OpenCV Mat.AddFloat", (*opencv.Mat).AddFloat, true)
	engine.RegisterMethod("opencv.subtractFloat", "OpenCV Mat.SubtractFloat", (*opencv.Mat).SubtractFloat, true)
	engine.RegisterMethod("opencv.multiplyFloat", "OpenCV Mat.MultiplyFloat", (*opencv.Mat).MultiplyFloat, true)
	engine.RegisterMethod("opencv.divideFloat", "OpenCV Mat.DivideFloat", (*opencv.Mat).DivideFloat, true)
	engine.RegisterMethod("opencv.multiplyMatrix", "OpenCV Mat.MultiplyMatrix", (*opencv.Mat).MultiplyMatrix, true)
	engine.RegisterMethod("opencv.t", "OpenCV Mat.T", (*opencv.Mat).T, true)
	engine.RegisterMethod("opencv.getVecbAt", "OpenCV Mat.GetVecbAt", (*opencv.Mat).GetVecbAt, true)
	engine.RegisterMethod("opencv.getVecfAt", "OpenCV Mat.GetVecfAt", (*opencv.Mat).GetVecfAt, true)
	engine.RegisterMethod("opencv.getVecdAt", "OpenCV Mat.GetVecdAt", (*opencv.Mat).GetVecdAt, true)
	engine.RegisterMethod("opencv.getVeciAt", "OpenCV Mat.GetVeciAt", (*opencv.Mat).GetVeciAt, true)
	engine.RegisterMethod("opencv.rowRange", "OpenCV Mat.RowRange", (*opencv.Mat).RowRange, true)
	engine.RegisterMethod("opencv.colRange", "OpenCV Mat.ColRange", (*opencv.Mat).ColRange, true)
	engine.RegisterMethod("opencv.toImage", "OpenCV Mat.ToImage", (*opencv.Mat).ToImage, true)
	engine.RegisterMethod("opencv.toImageYUV", "OpenCV Mat.ToImageYUV", (*opencv.Mat).ToImageYUV, true)
	engine.RegisterMethod("opencv.toImageYUVWithParams", "OpenCV Mat.ToImageYUVWithParams", (*opencv.Mat).ToImageYUVWithParams, true)
	engine.RegisterMethod("opencv.isNil", "OpenCV PointVector.IsNil", opencv.PointVector.IsNil, true)
	engine.RegisterMethod("opencv.at", "OpenCV PointVector.At", opencv.PointVector.At, true)
	engine.RegisterMethod("opencv.append", "OpenCV PointVector.Append", opencv.PointVector.Append, true)
	engine.RegisterMethod("opencv.toPoints", "OpenCV PointVector.ToPoints", opencv.PointVector.ToPoints, true)
	engine.RegisterMethod("opencv.p", "OpenCV PointsVector.P", opencv.PointsVector.P, true)
	engine.RegisterMethod("opencv.fill", "OpenCV RNG.Fill", (*opencv.RNG).Fill, true)
	engine.RegisterMethod("opencv.gaussian", "OpenCV RNG.Gaussian", (*opencv.RNG).Gaussian, true)
	engine.RegisterMethod("opencv.next", "OpenCV RNG.Next", (*opencv.RNG).Next, true)
	engine.RegisterMethod("opencv.getBytes", "OpenCV NativeByteBuffer.GetBytes", (*opencv.NativeByteBuffer).GetBytes, true)
	engine.RegisterMethod("opencv.len", "OpenCV NativeByteBuffer.Len", (*opencv.NativeByteBuffer).Len, true)
	engine.RegisterMethod("opencv.apply", "OpenCV CLAHE.Apply", (*opencv.CLAHE).Apply, true)
	return nil
}

// GetModule 返回模块实例。
func GetModule() model.Module { return &OpencvModule{} }
